from clinicedc_constants import (
    ANAEMIA,
    BACTERAEMIA_SEPSIS,
    BACTERIAL_PNEUMONIA,
    CM_RELAPSE_IRIS,
    COVID_19,
    CRYPTOCOCCAL_MENINGITIS,
    DEAD,
    MALIGNANCY,
    NEUTROPAENIA,
    NOT_APPLICABLE,
    OTHER,
    OTHER_PLEASE_SPECIFY_TEXT,
    PNEUMONIA,
    RENAL_IMPAIRMENT,
    TB_PULMONARY,
    THROMBOCYTOPENIA,
    TUBERCULOSIS,
    UNKNOWN,
)

list_data = {
    "edc_adverse_event.aeclassification": [
        ("cm_possible", "Possible cryptococcal meningitis"),
        ("cm_confirmed", "Confirmed cryptococcal meningitis"),
        ("cm_relapse_iris", "CM relapse/ IRIS"),
        ("confusion_delirium", "Altered mental state (confusion/ delirium)"),
        (ANAEMIA, "Anaemia"),
        (BACTERAEMIA_SEPSIS, "Bacteraemia/sepsis"),
        ("bacterial_meningitis", "Bacterial meningitis"),
        ("cerebrovascular_accident", "Cerebrovascular accident"),
        ("liver_injury_drug", "Drug-induced liver injury"),
        ("elevated_alp", "Elevated ALP"),
        ("elevated_ast", "Elevated AST"),
        ("gastroenteritis", "Gastroenteritis"),
        ("hyperbilirubinaemia_jaundice", "Hyperbilirubinaemia/ jaundice"),
        ("hypercalcaemia", "Hypercalcaemia"),
        ("hyperglycaemia", "Hyperglycaemia"),
        ("hyperkalaemia", "Hyperkalaemia"),
        ("hypernatraemia", "Hypernatraemia"),
        ("hyperuricaemia", "Hyperuricaemia"),
        ("hypertension", "Hypertension"),
        ("hypoalbuminaemia", "Hypoalbuminaemia"),
        ("hypocalcaemia", "Hypocalcaemia"),
        ("hypoglycaemia", "Hypoglycaemia"),
        ("hypokalaemia", "Hypokalaemia"),
        ("hypomagnesaemia", "Hypomagnesaemia"),
        ("hyponatraemia", "Hyponatraemia"),
        ("hypophosphataemia", "Hypophosphataemia"),
        ("intracranial_heamorrhage", "intracranial heamorrhage"),
        ("leucopaenia", "Leucopaenia"),
        ("metabolic_acidosis", "Metabolic acidosis"),
        (NEUTROPAENIA, "Neutropaenia"),
        ("pcp", "PCP"),
        (PNEUMONIA, "Pneumonia"),
        ("postdural_puncture_headache_nausea", "Post-dural puncture headache/ nausea"),
        (RENAL_IMPAIRMENT, "Renal impairment"),
        ("seizures", "Seizures"),
        (TUBERCULOSIS, "TB"),
        ("tb_meningitis", "TB meningitis"),
        (THROMBOCYTOPENIA, "Thrombocytopenia"),
        ("unintentional_weight_loss", "Unintentional weight loss"),
        ("venous_thromboembolism", "Venous thromboembolism (DVT and/or PE)"),
        (OTHER, "Other"),
        (NOT_APPLICABLE, "Not applicable"),
    ],
    "edc_adverse_event.saereason": [
        (NOT_APPLICABLE, "Not applicable"),
        (DEAD, "Death"),
        ("life_threatening", "Life-threatening"),
        ("significant_disability", "Significant disability"),
        ("in-patient_hospitalization", "In-patient hospitalization or prolongation"),
        (
            "medically_important_event",
            "Medically important event (e.g. Bacteraemia, "
            "recurrence of symptoms not requiring admission)",
        ),
    ],
    "edc_adverse_event.causeofdeath": [
        (CRYPTOCOCCAL_MENINGITIS, "Cryptococcal meningitis"),
        ("adv_hiv_susp_non_cns_io", "Advanced HIV with suspected undiagnosed non-CNS OI"),
        ("art_toxicity", "ART toxicity"),
        (BACTERAEMIA_SEPSIS, "Bacteraemia/sepsis"),
        (BACTERIAL_PNEUMONIA, "Bacterial pneumonia"),
        ("cns_infarction", "CNS infarction"),
        ("cns_infection_unsp", "CNS infection - unspecified"),
        (COVID_19, "COVID-19"),
        (CM_RELAPSE_IRIS, "Cryptococcal meningitis relapse/IRIS"),
        ("diarrhea_wasting", "Diarrhea/wasting"),
        ("intracranial_haemorrhage", "Intracranial haemorrhage"),
        ("iris_non_cm", "IRIS non-CM"),
        ("liver_failure", "Liver failure"),
        (MALIGNANCY, "Malignancy"),
        ("pcp", "PCP"),
        ("pneumonia_unknown_cause", "Pneumonia (cause unknown)"),
        ("pulmonary_embolism", "Pulmonary embolism - suspected/ confirmed"),
        ("renal_failure", "Renal failure"),
        ("tb_disseminated", "TB - Disseminated"),
        ("tb_meningitis", "TB - Meningitis"),
        (TB_PULMONARY, "TB - Pulmonary"),
        ("toxoplasmosis", "Toxoplasmosis"),
        (UNKNOWN, "Unknown"),
        (OTHER, OTHER_PLEASE_SPECIFY_TEXT),
    ],
}
