# Generated by Django 4.1.2 on 2022-12-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("effect_consent", "0006_auto_20220930_1306"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubjectconsent",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("af", "Afrikaans"),
                    ("mas", "Maasai"),
                    ("st", "Sotho"),
                    ("sw", "Swahili"),
                    ("tn", "Tswana"),
                    ("vie", "Vietnamese"),
                    ("xh", "Xhosa"),
                    ("zu", "Zulu"),
                ],
                help_text="The language used for the consent process will also be used during data collection.",
                max_length=25,
                verbose_name="Language of consent",
            ),
        ),
        migrations.AlterField(
            model_name="subjectconsent",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("af", "Afrikaans"),
                    ("mas", "Maasai"),
                    ("st", "Sotho"),
                    ("sw", "Swahili"),
                    ("tn", "Tswana"),
                    ("vie", "Vietnamese"),
                    ("xh", "Xhosa"),
                    ("zu", "Zulu"),
                ],
                help_text="The language used for the consent process will also be used during data collection.",
                max_length=25,
                verbose_name="Language of consent",
            ),
        ),
    ]
