# Generated by Django 4.2.5 on 2023-10-05 17:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("effect_consent", "0008_alter_subjectconsent_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subjectreconsent",
            options={
                "default_manager_name": "objects",
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "get_latest_by": "modified",
                "ordering": ("-modified", "-created"),
                "verbose_name": "Subject re-consent",
            },
        ),
    ]
