# Generated by Django 5.0 on 2024-01-11 01:57

from django.db import migrations
from django.db.migrations import RunPython


def update_model_name(apps, schema_editor):
    model_cls = apps.get_model("effect_consent.subjectconsent")
    model_cls.objects.update(model_name="effect_consent.subjectconsentug")


class Migration(migrations.Migration):
    dependencies = [
        ("effect_consent", "0011_historicalsubjectconsent_model_name_and_more"),
    ]

    operations = [RunPython(update_model_name)]
