# Generated by Django 4.2.6 on 2024-03-01 16:31

from django.db import migrations
from django.db.migrations import RunPython
from tqdm import tqdm


def fix_instance_model_names(apps, schema_editor):
    print("Fixing instance with model name: 'effect_consent.subjectconsentug' ...")
    model_cls = apps.get_model("effect_consent.subjectconsent")
    total = model_cls.objects.count()
    consent_model_name = "effect_consent.subjectconsent"
    for obj in tqdm(model_cls.objects.all(), total=total):
        if obj.model_name == "effect_consent.subjectconsentug":
            print(
                f" * Updating '{obj.subject_identifier}' consent model name "
                f"from '{obj.model_name}' to '{consent_model_name}'"
            )
            obj.model_name = "effect_consent.subjectconsent"
        else:
            print(
                f" * Skipping '{obj.subject_identifier}' "
                f"with consent model name '{obj.model_name}'"
            )


class Migration(migrations.Migration):

    dependencies = [
        ("effect_consent", "0018_alter_historicalsubjectconsent_options_and_more"),
    ]

    operations = [RunPython(fix_instance_model_names)]
