# Generated by Django 3.2.13 on 2022-07-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("effect_screening", "0024_auto_20220614_1749"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalsubjectscreening",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Subject Screening",
                "verbose_name_plural": "historical Subject Screening",
            },
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
