# Generated by Django 4.2.6 on 2024-03-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_screening", "0040_feat_731_unsuitable_reason_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="reasons_unsuitable",
            field=models.TextField(
                default="QUESTION_RETIRED",
                editable=False,
                help_text="question_retired",
                max_length=150,
                verbose_name="Reason not suitable for the study",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="reasons_unsuitable",
            field=models.TextField(
                default="QUESTION_RETIRED",
                editable=False,
                help_text="question_retired",
                max_length=150,
                verbose_name="Reason not suitable for the study",
            ),
        ),
    ]
