# Generated by Django 5.2.4 on 2025-09-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_screening", "0051_alter_historicalsubjectscreening_revision_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsubjectscreening",
            name="ethnicity",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="subjectscreening",
            name="ethnicity",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
