# Generated by Django 5.2.6 on 2025-09-17 16:53

import edc_model_fields.fields.other_charfield
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_screening", "0052_historicalsubjectscreening_ethnicity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="any_other_mg_ssx_other",
            field=models.TextField(
                blank=True,
                default="",
                help_text="If more than one, please separate each with a comma (,).",
                verbose_name="If YES, specify",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="cm_in_csf_method_other",
            field=edc_model_fields.fields.other_charfield.OtherCharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="If other, please specify ...",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="device_created",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Device created"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="device_modified",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Device modified"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="ethnicity",
            field=models.CharField(blank=True, default="", max_length=25),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="hiv_pos",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("not_evaluated", "Not evaluated"),
                ],
                default="not_evaluated",
                max_length=15,
                verbose_name="Is the patient CONFIRMED HIV sero-positive?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="locale_created",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                verbose_name="Locale created",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="lp_done",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="",
                help_text="If YES, provide date below ...",
                max_length=15,
                verbose_name="Was LP done?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="reasons_ineligible",
            field=models.TextField(
                default="", max_length=150, verbose_name="Reason not eligible"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="slug",
            field=models.CharField(
                db_index=True,
                default="",
                editable=False,
                help_text="a field used for quick search",
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="subject_identifier_aka",
            field=models.CharField(
                default="",
                editable=False,
                help_text="track a previously allocated identifier.",
                max_length=50,
                verbose_name="Subject Identifier a.k.a",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="unsuitable_reason_other",
            field=models.TextField(
                blank=True,
                default="",
                max_length=150,
                verbose_name="If other reason unsuitable, please specify ...",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="any_other_mg_ssx_other",
            field=models.TextField(
                blank=True,
                default="",
                help_text="If more than one, please separate each with a comma (,).",
                verbose_name="If YES, specify",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="cm_in_csf_method_other",
            field=edc_model_fields.fields.other_charfield.OtherCharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="If other, please specify ...",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="device_created",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Device created"
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="device_modified",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Device modified"
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="ethnicity",
            field=models.CharField(blank=True, default="", max_length=25),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="hiv_pos",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("not_evaluated", "Not evaluated"),
                ],
                default="not_evaluated",
                max_length=15,
                verbose_name="Is the patient CONFIRMED HIV sero-positive?",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="locale_created",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                verbose_name="Locale created",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="lp_done",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="",
                help_text="If YES, provide date below ...",
                max_length=15,
                verbose_name="Was LP done?",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="reasons_ineligible",
            field=models.TextField(
                default="", max_length=150, verbose_name="Reason not eligible"
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="slug",
            field=models.CharField(
                db_index=True,
                default="",
                editable=False,
                help_text="a field used for quick search",
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="subject_identifier_aka",
            field=models.CharField(
                default="",
                editable=False,
                help_text="track a previously allocated identifier.",
                max_length=50,
                verbose_name="Subject Identifier a.k.a",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="unsuitable_reason_other",
            field=models.TextField(
                blank=True,
                default="",
                max_length=150,
                verbose_name="If other reason unsuitable, please specify ...",
            ),
        ),
    ]
