# Generated by Django 5.2.6 on 2025-09-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "effect_screening",
            "0054_alter_historicalsubjectscreening_report_datetime_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="slug",
            field=models.CharField(
                db_index=True,
                default="",
                editable=False,
                help_text="Hold slug field values for quick search. Excludes encrypted fields",
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="slug",
            field=models.CharField(
                db_index=True,
                default="",
                editable=False,
                help_text="Hold slug field values for quick search. Excludes encrypted fields",
                max_length=250,
            ),
        ),
    ]
