# Generated by Django 6.0.4 on 2026-04-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_screening", "0056_alter_historicalsubjectscreening_revision_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsubjectscreening",
            name="dm_comment",
            field=models.TextField(
                default="",
                help_text="For data manager only",
                verbose_name="Data management comment",
            ),
        ),
        migrations.AddField(
            model_name="subjectscreening",
            name="dm_comment",
            field=models.TextField(
                default="",
                help_text="For data manager only",
                verbose_name="Data management comment",
            ),
        ),
    ]
