# Generated by Django 6.0.4 on 2026-04-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_screening", "0057_historicalsubjectscreening_dm_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="dm_comment",
            field=models.TextField(
                blank=True,
                default="",
                help_text="For data manager only",
                verbose_name="Data management comment",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="dm_comment",
            field=models.TextField(
                blank=True,
                default="",
                help_text="For data manager only",
                verbose_name="Data management comment",
            ),
        ),
    ]
