DEFINITELY_RELATED = "definitely_related"
DISCHARGED = "discharged"
INPATIENT = "inpatient"
NOT_RELATED = "not_related"
POSSIBLY_RELATED = "possibly_related"
PROBABLY_RELATED = "probably_related"
UNLIKELY_RELATED = "unlikely_related"
