# Generated by Django 3.2.8 on 2022-05-16 12:20

import edc_model.validators.date
import edc_protocol.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("effect_prn", "0004_historicalhospitalization_hospitalization"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalhospitalization",
            name="csf_positive_cm",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("unknown", "Unknown"),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                max_length=15,
                verbose_name="If YES, was CSF positive for CM?",
            ),
        ),
        migrations.AddField(
            model_name="historicalhospitalization",
            name="csf_positive_cm_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    edc_model.validators.date.date_not_future,
                    edc_protocol.validators.date_not_before_study_start,
                ],
                verbose_name="If YES, date of positive CSF",
            ),
        ),
        migrations.AddField(
            model_name="hospitalization",
            name="csf_positive_cm",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("unknown", "Unknown"),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                max_length=15,
                verbose_name="If YES, was CSF positive for CM?",
            ),
        ),
        migrations.AddField(
            model_name="hospitalization",
            name="csf_positive_cm_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    edc_model.validators.date.date_not_future,
                    edc_protocol.validators.date_not_before_study_start,
                ],
                verbose_name="If YES, date of positive CSF",
            ),
        ),
    ]
