# Generated by Django 3.2.11 on 2022-02-28 17:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("effect_lists", "0004_auto_20220223_2142"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RankinScore",
        ),
    ]
