# Generated by Django 3.2.8 on 2022-04-14 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("effect_subject", "0034_auto_20220414_1202"),
        ("effect_lists", "0007_auto_20220330_1707"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MedicinesDay14",
        ),
    ]
