# Generated by Django 5.0 on 2023-12-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "effect_lists",
            "0014_antibiotics_extra_value_arvregimens_extra_value_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="antibiotics",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Antibiotics",
                "verbose_name_plural": "Antibiotics",
            },
        ),
        migrations.AlterModelOptions(
            name="arvregimens",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "ARV Regimens",
                "verbose_name_plural": "ARV Regimens",
            },
        ),
        migrations.AlterModelOptions(
            name="dosemodificationreasons",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Dose Modification Reasons",
                "verbose_name_plural": "Dose Modification Reasons",
            },
        ),
        migrations.AlterModelOptions(
            name="drugs",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Drugs",
                "verbose_name_plural": "Drugs",
            },
        ),
        migrations.AlterModelOptions(
            name="dx",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Diagnoses",
                "verbose_name_plural": "Diagnoses",
            },
        ),
        migrations.AlterModelOptions(
            name="lateexclusioncriteria",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Late Exclusion Criteria",
                "verbose_name_plural": "Late Exclusion Criteria",
            },
        ),
        migrations.AlterModelOptions(
            name="medication",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Medication",
                "verbose_name_plural": "Medication",
            },
        ),
        migrations.AlterModelOptions(
            name="nonadherencereasons",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Non-Adherence Reasons",
                "verbose_name_plural": "Non-Adherence Reasons",
            },
        ),
        migrations.AlterModelOptions(
            name="offstudyreasons",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Offstudy Reasons",
                "verbose_name_plural": "Offstudy Reasons",
            },
        ),
        migrations.AlterModelOptions(
            name="sisx",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Signs and Symptoms",
                "verbose_name_plural": "Signs and Symptoms",
            },
        ),
        migrations.AlterModelOptions(
            name="sisxmeningitis",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Signs and Symptoms (Meningitis)",
                "verbose_name_plural": "Signs and Symptoms (Meningitis)",
            },
        ),
        migrations.AlterModelOptions(
            name="subjectvisitmissedreasons",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Subject Missed Visit Reasons",
                "verbose_name_plural": "Subject Missed Visit Reasons",
            },
        ),
        migrations.AlterModelOptions(
            name="tbtreatments",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "TB Treatments",
                "verbose_name_plural": "TB Treatments",
            },
        ),
        migrations.AlterModelOptions(
            name="transport",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Transport",
                "verbose_name_plural": "Transport",
            },
        ),
        migrations.AlterModelOptions(
            name="xrayresults",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "X-Ray Results",
                "verbose_name_plural": "X-Ray Results",
            },
        ),
        migrations.RemoveIndex(
            model_name="antibiotics",
            name="effect_list_id_15f747_idx",
        ),
        migrations.RemoveIndex(
            model_name="arvregimens",
            name="effect_list_id_5eee26_idx",
        ),
        migrations.RemoveIndex(
            model_name="dosemodificationreasons",
            name="effect_list_id_c7a8ed_idx",
        ),
        migrations.RemoveIndex(
            model_name="drugs",
            name="effect_list_id_13a5ac_idx",
        ),
        migrations.RemoveIndex(
            model_name="dx",
            name="effect_list_id_b7cc84_idx",
        ),
        migrations.RemoveIndex(
            model_name="lateexclusioncriteria",
            name="effect_list_id_c243ef_idx",
        ),
        migrations.RemoveIndex(
            model_name="medication",
            name="effect_list_id_9557c7_idx",
        ),
        migrations.RemoveIndex(
            model_name="nonadherencereasons",
            name="effect_list_id_59f575_idx",
        ),
        migrations.RemoveIndex(
            model_name="offstudyreasons",
            name="effect_list_id_5ec080_idx",
        ),
        migrations.RemoveIndex(
            model_name="sisx",
            name="effect_list_id_932263_idx",
        ),
        migrations.RemoveIndex(
            model_name="sisxmeningitis",
            name="effect_list_id_3e3554_idx",
        ),
        migrations.RemoveIndex(
            model_name="subjectvisitmissedreasons",
            name="effect_list_id_16bf01_idx",
        ),
        migrations.RemoveIndex(
            model_name="tbtreatments",
            name="effect_list_id_b5ffb6_idx",
        ),
        migrations.RemoveIndex(
            model_name="transport",
            name="effect_list_id_739311_idx",
        ),
        migrations.RemoveIndex(
            model_name="xrayresults",
            name="effect_list_id_467d5f_idx",
        ),
        migrations.AlterField(
            model_name="antibiotics",
            name="display_index",
            field=models.IntegerField(
                default=0,
                help_text="Index to control display order if not alphabetical, not required",
                verbose_name="display index",
            ),
        ),
        migrations.AlterField(
            model_name="antibiotics",
            name="display_name",
            field=models.CharField(
                help_text="(suggest 40 characters max.)",
                max_length=250,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="antibiotics",
            name="name",
            field=models.CharField(
                help_text="This is the stored value, required",
                max_length=250,
                unique=True,
                verbose_name="Stored value",
            ),
        ),
        migrations.AlterField(
            model_name="arvregimens",
            name="display_index",
            field=models.IntegerField(
                default=0,
                help_text="Index to control display order if not alphabetical, not required",
                verbose_name="display index",
            ),
        ),
        migrations.AlterField(
            model_name="arvregimens",
            name="display_name",
            field=models.CharField(
                help_text="(suggest 40 characters max.)",
                max_length=250,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="arvregimens",
            name="name",
            field=models.CharField(
                help_text="This is the stored value, required",
                max_length=250,
                unique=True,
                verbose_name="Stored value",
            ),
        ),
        migrations.AlterField(
            model_name="dosemodificationreasons",
            name="display_index",
            field=models.IntegerField(
                default=0,
                help_text="Index to control display order if not alphabetical, not required",
                verbose_name="display index",
            ),
        ),
        migrations.AlterField(
            model_name="dosemodificationreasons",
            name="display_name",
            field=models.CharField(
                help_text="(suggest 40 characters max.)",
                max_length=250,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="dosemodificationreasons",
            name="name",
            field=models.CharField(
                help_text="This is the stored value, required",
                max_length=250,
                unique=True,
                verbose_name="Stored value",
            ),
        ),
        migrations.AlterField(
            model_name="drugs",
            name="display_index",
            field=models.IntegerField(
                default=0,
                help_text="Index to control display order if not alphabetical, not required",
                verbose_name="display index",
            ),
        ),
        migrations.AlterField(
            model_name="drugs",
            name="display_name",
            field=models.CharField(
                help_text="(suggest 40 characters max.)",
                max_length=250,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="drugs",
            name="name",
            field=models.CharField(
                help_text="This is the stored value, required",
                max_length=250,
                unique=True,
                verbose_name="Stored value",
            ),
        ),
        migrations.AlterField(
            model_name="dx",
            name="display_index",
            field=models.IntegerField(
                default=0,
                help_text="Index to control display order if not alphabetical, not required",
                verbose_name="display index",
            ),
        ),
        migrations.AlterField(
            model_name="dx",
            name="display_name",
            field=models.CharField(
                help_text="(suggest 40 characters max.)",
                max_length=250,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="dx",
            name="name",
            field=models.CharField(
                help_text="This is the stored value, required",
                max_length=250,
                unique=True,
                verbose_name="Stored value",
            ),
        ),
        migrations.AlterField(
            model_name="lateexclusioncriteria",
            name="display_index",
            field=models.IntegerField(
                default=0,
                help_text="Index to control display order if not alphabetical, not required",
                verbose_name="display index",
            ),
        ),
        migrations.AlterField(
            model_name="lateexclusioncriteria",
            name="display_name",
            field=models.CharField(
                help_text="(suggest 40 characters max.)",
                max_length=250,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="lateexclusioncriteria",
            name="name",
            field=models.CharField(
                help_text="This is the stored value, required",
                max_length=250,
                unique=True,
                verbose_name="Stored value",
            ),
        ),
        migrations.AlterField(
            model_name="medication",
            name="display_index",
            field=models.IntegerField(
                default=0,
                help_text="Index to control display order if not alphabetical, not required",
                verbose_name="display index",
            ),
        ),
        migrations.AlterField(
            model_name="medication",
            name="display_name",
            field=models.CharField(
                help_text="(suggest 40 characters max.)",
                max_length=250,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="medication",
            name="name",
            field=models.CharField(
                help_text="This is the stored value, required",
                max_length=250,
                unique=True,
                verbose_name="Stored value",
            ),
        ),
        migrations.AlterField(
            model_name="nonadherencereasons",
            name="display_index",
            field=models.IntegerField(
                default=0,
                help_text="Index to control display order if not alphabetical, not required",
                verbose_name="display index",
            ),
        ),
        migrations.AlterField(
            model_name="nonadherencereasons",
            name="display_name",
            field=models.CharField(
                help_text="(suggest 40 characters max.)",
                max_length=250,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="nonadherencereasons",
            name="name",
            field=models.CharField(
                help_text="This is the stored value, required",
                max_length=250,
                unique=True,
                verbose_name="Stored value",
            ),
        ),
        migrations.AlterField(
            model_name="offstudyreasons",
            name="display_index",
            field=models.IntegerField(
                default=0,
                help_text="Index to control display order if not alphabetical, not required",
                verbose_name="display index",
            ),
        ),
        migrations.AlterField(
            model_name="offstudyreasons",
            name="display_name",
            field=models.CharField(
                help_text="(suggest 40 characters max.)",
                max_length=250,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="offstudyreasons",
            name="name",
            field=models.CharField(
                help_text="This is the stored value, required",
                max_length=250,
                unique=True,
                verbose_name="Stored value",
            ),
        ),
        migrations.AlterField(
            model_name="sisx",
            name="display_index",
            field=models.IntegerField(
                default=0,
                help_text="Index to control display order if not alphabetical, not required",
                verbose_name="display index",
            ),
        ),
        migrations.AlterField(
            model_name="sisx",
            name="display_name",
            field=models.CharField(
                help_text="(suggest 40 characters max.)",
                max_length=250,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="sisx",
            name="name",
            field=models.CharField(
                help_text="This is the stored value, required",
                max_length=250,
                unique=True,
                verbose_name="Stored value",
            ),
        ),
        migrations.AlterField(
            model_name="sisxmeningitis",
            name="display_index",
            field=models.IntegerField(
                default=0,
                help_text="Index to control display order if not alphabetical, not required",
                verbose_name="display index",
            ),
        ),
        migrations.AlterField(
            model_name="sisxmeningitis",
            name="display_name",
            field=models.CharField(
                help_text="(suggest 40 characters max.)",
                max_length=250,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="sisxmeningitis",
            name="name",
            field=models.CharField(
                help_text="This is the stored value, required",
                max_length=250,
                unique=True,
                verbose_name="Stored value",
            ),
        ),
        migrations.AlterField(
            model_name="subjectvisitmissedreasons",
            name="display_index",
            field=models.IntegerField(
                default=0,
                help_text="Index to control display order if not alphabetical, not required",
                verbose_name="display index",
            ),
        ),
        migrations.AlterField(
            model_name="subjectvisitmissedreasons",
            name="display_name",
            field=models.CharField(
                help_text="(suggest 40 characters max.)",
                max_length=250,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="subjectvisitmissedreasons",
            name="name",
            field=models.CharField(
                help_text="This is the stored value, required",
                max_length=250,
                unique=True,
                verbose_name="Stored value",
            ),
        ),
        migrations.AlterField(
            model_name="tbtreatments",
            name="display_index",
            field=models.IntegerField(
                default=0,
                help_text="Index to control display order if not alphabetical, not required",
                verbose_name="display index",
            ),
        ),
        migrations.AlterField(
            model_name="tbtreatments",
            name="display_name",
            field=models.CharField(
                help_text="(suggest 40 characters max.)",
                max_length=250,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="tbtreatments",
            name="name",
            field=models.CharField(
                help_text="This is the stored value, required",
                max_length=250,
                unique=True,
                verbose_name="Stored value",
            ),
        ),
        migrations.AlterField(
            model_name="transport",
            name="display_index",
            field=models.IntegerField(
                default=0,
                help_text="Index to control display order if not alphabetical, not required",
                verbose_name="display index",
            ),
        ),
        migrations.AlterField(
            model_name="transport",
            name="display_name",
            field=models.CharField(
                help_text="(suggest 40 characters max.)",
                max_length=250,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="transport",
            name="name",
            field=models.CharField(
                help_text="This is the stored value, required",
                max_length=250,
                unique=True,
                verbose_name="Stored value",
            ),
        ),
        migrations.AlterField(
            model_name="xrayresults",
            name="display_index",
            field=models.IntegerField(
                default=0,
                help_text="Index to control display order if not alphabetical, not required",
                verbose_name="display index",
            ),
        ),
        migrations.AlterField(
            model_name="xrayresults",
            name="display_name",
            field=models.CharField(
                help_text="(suggest 40 characters max.)",
                max_length=250,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="xrayresults",
            name="name",
            field=models.CharField(
                help_text="This is the stored value, required",
                max_length=250,
                unique=True,
                verbose_name="Stored value",
            ),
        ),
        migrations.AddIndex(
            model_name="antibiotics",
            index=models.Index(
                fields=["display_index", "display_name"],
                name="effect_list_display_2e490d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="arvregimens",
            index=models.Index(
                fields=["display_index", "display_name"],
                name="effect_list_display_6f7d7d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dosemodificationreasons",
            index=models.Index(
                fields=["display_index", "display_name"],
                name="effect_list_display_cba0d7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="drugs",
            index=models.Index(
                fields=["display_index", "display_name"],
                name="effect_list_display_1a58ed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dx",
            index=models.Index(
                fields=["display_index", "display_name"],
                name="effect_list_display_d68fd4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lateexclusioncriteria",
            index=models.Index(
                fields=["display_index", "display_name"],
                name="effect_list_display_113280_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medication",
            index=models.Index(
                fields=["display_index", "display_name"],
                name="effect_list_display_f4cb40_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="nonadherencereasons",
            index=models.Index(
                fields=["display_index", "display_name"],
                name="effect_list_display_711023_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="offstudyreasons",
            index=models.Index(
                fields=["display_index", "display_name"],
                name="effect_list_display_775286_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sisx",
            index=models.Index(
                fields=["display_index", "display_name"],
                name="effect_list_display_1da790_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sisxmeningitis",
            index=models.Index(
                fields=["display_index", "display_name"],
                name="effect_list_display_1867ff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subjectvisitmissedreasons",
            index=models.Index(
                fields=["display_index", "display_name"],
                name="effect_list_display_523bbb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tbtreatments",
            index=models.Index(
                fields=["display_index", "display_name"],
                name="effect_list_display_b8e56f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transport",
            index=models.Index(
                fields=["display_index", "display_name"],
                name="effect_list_display_0d61e2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="xrayresults",
            index=models.Index(
                fields=["display_index", "display_name"],
                name="effect_list_display_c82ea6_idx",
            ),
        ),
    ]
