# Generated by Django 4.2.11 on 2024-08-15 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("effect_reports", "0001_initial"),
    ]

    operations = []
