# Generated by Django 5.1.1 on 2024-09-13 11:43

from django.db import migrations
from edc_qareports.utils import read_unmanaged_model_sql


class Migration(migrations.Migration):
    dependencies = [
        ("effect_reports", "0006_auto_20240913_1115"),
    ]

    operations = []
