# Generated by Django 5.1.1 on 2024-09-13 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("effect_reports", "0006_auto_20240913_1115"),
    ]

    operations = []
