# Generated by Django 5.1.3 on 2024-12-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("effect_reports", "0008_alter_serumcragdate_created"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalserumcragdatenote",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Redmine #488.2 - Serum Crag Date Note",
                "verbose_name_plural": "historical Redmine #488.2 - Serum Crag Date Notes",
            },
        ),
        migrations.AlterModelOptions(
            name="rm792kwincurrentsxgteg3other",
            options={
                "default_permissions": ("view", "export", "viewallsites"),
                "managed": False,
                "verbose_name": "Redmine #792.2 - Signs and Symptoms: Keyword in other G3 sx",
                "verbose_name_plural": "Redmine #792.2 - Signs and Symptoms: Keyword in other G3 sx",
            },
        ),
        migrations.AlterModelOptions(
            name="rm792kwincurrentsxother",
            options={
                "default_permissions": ("view", "export", "viewallsites"),
                "managed": False,
                "verbose_name": "Redmine #792.1 - Signs and Symptoms: Keyword in other sx",
                "verbose_name_plural": "Redmine #792.1 - Signs and Symptoms: Keyword in other sx",
            },
        ),
        migrations.AlterModelOptions(
            name="rm792sisxlistcandidates",
            options={
                "default_permissions": ("view", "export", "viewallsites"),
                "managed": False,
                "verbose_name": "Redmine #792.3 - Signs and Symptoms: Possible list candidates",
                "verbose_name_plural": "Redmine #792.3 - Signs and Symptoms: Possible list candidates",
            },
        ),
        migrations.AlterModelOptions(
            name="serumcragdate",
            options={
                "default_permissions": ("view", "export", "viewallsites"),
                "verbose_name": "Redmine #488.1 - Serum Crag Date (Confirmation)",
                "verbose_name_plural": "Redmine #488.1 - Serum Crag Dates (Confirmation)",
            },
        ),
        migrations.AlterModelOptions(
            name="serumcragdatenote",
            options={
                "default_manager_name": "objects",
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "verbose_name": "Redmine #488.2 - Serum Crag Date Note",
                "verbose_name_plural": "Redmine #488.2 - Serum Crag Date Notes",
            },
        ),
    ]
