# Generated by Django 5.1.3 on 2025-01-23 11:46

from django.db import migrations
from edc_qareports.utils import read_unmanaged_model_sql


class Migration(migrations.Migration):
    dependencies = [
        ("effect_reports", "0011_alter_baselinevldiscrepancy_options_and_more"),
    ]

    operations = []
