# Generated by Django 5.1.3 on 2025-01-23 11:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("effect_reports", "0011_alter_baselinevldiscrepancy_options_and_more"),
    ]

    operations = []
