# Generated by Django 5.1.3 on 2025-01-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_reports", "0012_update_rm792_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="baselinevlall",
            name="visit_code",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="baselinevlall",
            name="visit_code_sequence",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="baselinevldiscrepancy",
            name="visit_code",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="baselinevldiscrepancy",
            name="visit_code_sequence",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="baselinevlmissingquantifier",
            name="visit_code",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="baselinevlmissingquantifier",
            name="visit_code_sequence",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
