# Generated by Django 5.2.6 on 2025-09-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_reports", "0014_alter_baselinevlall_revision_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baselinevlall",
            name="device_created",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Device created"
            ),
        ),
        migrations.AlterField(
            model_name="baselinevlall",
            name="device_modified",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Device modified"
            ),
        ),
        migrations.AlterField(
            model_name="baselinevlall",
            name="has_viral_load_result",
            field=models.CharField(default="", max_length=5),
        ),
        migrations.AlterField(
            model_name="baselinevlall",
            name="locale_created",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                verbose_name="Locale created",
            ),
        ),
        migrations.AlterField(
            model_name="baselinevlall",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AlterField(
            model_name="baselinevlall",
            name="user_created",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="baselinevlall",
            name="user_modified",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="baselinevlall",
            name="viral_load_date_estimated",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="baselinevlall",
            name="viral_load_quantifier",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="baselinevlall",
            name="visit_code",
            field=models.CharField(default="", max_length=25),
        ),
        migrations.AlterField(
            model_name="baselinevlall",
            name="visit_code_sequence",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="baselinevldiscrepancy",
            name="device_created",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Device created"
            ),
        ),
        migrations.AlterField(
            model_name="baselinevldiscrepancy",
            name="device_modified",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Device modified"
            ),
        ),
        migrations.AlterField(
            model_name="baselinevldiscrepancy",
            name="has_viral_load_result",
            field=models.CharField(default="", max_length=5),
        ),
        migrations.AlterField(
            model_name="baselinevldiscrepancy",
            name="locale_created",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                verbose_name="Locale created",
            ),
        ),
        migrations.AlterField(
            model_name="baselinevldiscrepancy",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AlterField(
            model_name="baselinevldiscrepancy",
            name="user_created",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="baselinevldiscrepancy",
            name="user_modified",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="baselinevldiscrepancy",
            name="viral_load_date_estimated",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="baselinevldiscrepancy",
            name="viral_load_quantifier",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="baselinevldiscrepancy",
            name="visit_code",
            field=models.CharField(default="", max_length=25),
        ),
        migrations.AlterField(
            model_name="baselinevldiscrepancy",
            name="visit_code_sequence",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="baselinevlmissingquantifier",
            name="device_created",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Device created"
            ),
        ),
        migrations.AlterField(
            model_name="baselinevlmissingquantifier",
            name="device_modified",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Device modified"
            ),
        ),
        migrations.AlterField(
            model_name="baselinevlmissingquantifier",
            name="has_viral_load_result",
            field=models.CharField(default="", max_length=5),
        ),
        migrations.AlterField(
            model_name="baselinevlmissingquantifier",
            name="locale_created",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                verbose_name="Locale created",
            ),
        ),
        migrations.AlterField(
            model_name="baselinevlmissingquantifier",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AlterField(
            model_name="baselinevlmissingquantifier",
            name="user_created",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="baselinevlmissingquantifier",
            name="user_modified",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="baselinevlmissingquantifier",
            name="viral_load_date_estimated",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="baselinevlmissingquantifier",
            name="viral_load_quantifier",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="baselinevlmissingquantifier",
            name="visit_code",
            field=models.CharField(default="", max_length=25),
        ),
        migrations.AlterField(
            model_name="baselinevlmissingquantifier",
            name="visit_code_sequence",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="historicalserumcragdatenote",
            name="device_created",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Device created"
            ),
        ),
        migrations.AlterField(
            model_name="historicalserumcragdatenote",
            name="device_modified",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Device modified"
            ),
        ),
        migrations.AlterField(
            model_name="historicalserumcragdatenote",
            name="locale_created",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                verbose_name="Locale created",
            ),
        ),
        migrations.AlterField(
            model_name="historicalserumcragdatenote",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AlterField(
            model_name="historicalserumcragdatenote",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="serumcragdate",
            name="screening_identifier",
            field=models.CharField(
                default="", max_length=50, verbose_name="Screening ID"
            ),
        ),
        migrations.AlterField(
            model_name="serumcragdate",
            name="serum_crag_value",
            field=models.CharField(default="", max_length=50, verbose_name="CrAg"),
        ),
        migrations.AlterField(
            model_name="serumcragdatenote",
            name="device_created",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Device created"
            ),
        ),
        migrations.AlterField(
            model_name="serumcragdatenote",
            name="device_modified",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Device modified"
            ),
        ),
        migrations.AlterField(
            model_name="serumcragdatenote",
            name="locale_created",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                verbose_name="Locale created",
            ),
        ),
        migrations.AlterField(
            model_name="serumcragdatenote",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AlterField(
            model_name="serumcragdatenote",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
