# Generated by Django 5.2.6 on 2025-09-18 00:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_reports", "0015_alter_baselinevlall_device_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalserumcragdatenote",
            name="report_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="serumcragdate",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="serumcragdatenote",
            name="report_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
