# Generated by Django 5.2.10 on 2026-03-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_reports", "0018_auto_20250925_1041"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baselinevlall",
            options={
                "default_permissions": ("view", "export", "viewallsites"),
                "managed": False,
                "verbose_name": "Redmine #658.1 - Baseline Viral Load (All)",
                "verbose_name_plural": "Redmine #658.1 - Baseline Viral Loads (All)",
            },
        ),
        migrations.AlterModelOptions(
            name="baselinevlmissingquantifier",
            options={
                "default_permissions": ("view", "export", "viewallsites"),
                "managed": False,
                "verbose_name": "Redmine #658.2 - Baseline Viral Load (Missing VL Quantifier)",
                "verbose_name_plural": "Redmine #658.2 - Baseline Viral Loads (Missing VL Quantifier)",
            },
        ),
        migrations.AddField(
            model_name="historicalserumcragdatenote",
            name="label",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="historicalserumcragdatenote",
            name="visit_code",
            field=models.CharField(blank=True, default="", max_length=25),
        ),
        migrations.AddField(
            model_name="historicalserumcragdatenote",
            name="visit_code_sequence",
            field=models.IntegerField(blank=True, default=0, verbose_name="Sequence"),
        ),
        migrations.AddField(
            model_name="serumcragdate",
            name="label",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="serumcragdate",
            name="visit_code",
            field=models.CharField(default="", max_length=25),
        ),
        migrations.AddField(
            model_name="serumcragdate",
            name="visit_code_sequence",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="serumcragdatenote",
            name="label",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="serumcragdatenote",
            name="visit_code",
            field=models.CharField(blank=True, default="", max_length=25),
        ),
        migrations.AddField(
            model_name="serumcragdatenote",
            name="visit_code_sequence",
            field=models.IntegerField(blank=True, default=0, verbose_name="Sequence"),
        ),
        migrations.AlterModelTable(
            name="onstudymissinglabvalues",
            table="effect_reports_onstudymissinglabvaluesview",
        ),
        migrations.AlterModelTable(
            name="rm792kwincurrentsxgteg3other",
            table="effect_reports_rm792kwincurrentsxgteg3otherview",
        ),
        migrations.AlterModelTable(
            name="rm792kwincurrentsxother",
            table="effect_reports_rm792kwincurrentsxotherview",
        ),
        migrations.AlterModelTable(
            name="rm792sisxlistcandidates",
            table="effect_reports_rm792sisxlistcandidatesview",
        ),
        migrations.DeleteModel(
            name="BaselineVlDiscrepancy",
        ),
    ]
