# Generated by Django 5.2.10 on 2026-03-18 22:22

import sys

from django.db import migrations, transaction
from django.db.models import Count, Q
from tqdm import tqdm

from clinicedc_constants import NULL_STRING
from edc_qareports.models import Note
from django.apps import apps as django_apps


def update_note_models(apps, schema_editor):
    Note.objects.filter(
        report_model="onstudy_missing_lab_values_view").update(
        report_model="effect_reports.onstudymissinglabvalues")
    sys.stdout.write("Updating visit_code on Note model...\n")
    for report_models in (
            Note.objects.values("report_model").annotate(total=Count("id")).order_by()
    ):
        report_model = report_models.get("report_model")
        try:
            model_cls = django_apps.get_model(report_model)
        except ValueError:
            report_model = f"effect_reports.{report_models.get('report_model').replace('_', '').replace('view', '')}"
            model_cls = django_apps.get_model(report_model)
        print(report_model)
        report_query = model_cls.objects.exclude(visit_code__isnull=True)
        for report_obj in tqdm(report_query, total=report_query.count()):
            with transaction.atomic():
                try:
                    note_obj = Note.objects.get(
                        Q(visit_code=NULL_STRING) | Q(visit_code__isnull=True),
                        report_model=model_cls._meta.label_lower,
                        subject_identifier=report_obj.subject_identifier,
                        label=report_obj.label,
                    )
                except Note.DoesNotExist:
                    pass
                else:
                    note_obj.visit_code = report_obj.visit_code or NULL_STRING
                    note_obj.visit_code_sequence = report_obj.visit_code_sequence or 0
                    note_obj.label = report_obj.label
                    note_obj.report_model = report_model
                    note_obj.save()

    sys.stdout.write("Done.\n")


class Migration(migrations.Migration):
    dependencies = [
        (
            "edc_qareports",
            "0025_remove_note_edc_qareports_note_report_model_subj_uniq_and_more",
        ),
        ("effect_reports", "0020_auto_20260319_0128"),
    ]

    operations = [migrations.RunPython(update_note_models)]
