# Generated by Django 5.2.10 on 2026-04-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_reports", "0021_auto_20260319_0128"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalserumcragdatenote",
            name="label",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="serumcragdatenote",
            name="label",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AlterModelTable(
            name="baselinevlall",
            table="effect_reports_baselinevlallview",
        ),
        migrations.AlterModelTable(
            name="baselinevlmissingquantifier",
            table="effect_reports_baselinevlmissingquantifierview",
        ),
    ]
