# Generated by Django 6.0.4 on 2026-05-08 01:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_reports", "0022_alter_historicalserumcragdatenote_label_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArvSummaryReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_model", models.CharField(max_length=50)),
                ("subject_identifier", models.CharField(max_length=25)),
                ("visit_code", models.CharField(default="", max_length=25)),
                ("visit_code_sequence", models.IntegerField(null=True)),
                ("label", models.CharField(max_length=150, null=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Arv summary to complete",
                "verbose_name_plural": "ARV Summarys to complete",
                "db_table": "effect_reports_arvsummaryview",
                "managed": False,
                "default_permissions": ("view", "export", "viewallsites"),
            },
        ),
    ]
