# Generated by Django 4.2.11 on 2024-08-02 11:13

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sites", "0002_alter_domain_unique"),
        ("effect_reports", "0002_auto_20240626_1725"),
    ]

    operations = [
        migrations.CreateModel(
            name="SerumCragDateConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("report_model", models.CharField(max_length=50)),
                ("subject_identifier", models.CharField(max_length=25)),
                ("created", models.DateTimeField()),
                (
                    "screening_identifier",
                    models.CharField(max_length=50, null=True, verbose_name="Screening ID"),
                ),
                ("report_date", models.DateField(null=True)),
                ("serum_crag_date", models.DateField(null=True)),
                ("eligibility_date", models.DateField(null=True)),
                (
                    "serum_crag_value",
                    models.CharField(max_length=50, null=True, verbose_name="CrAg"),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sites.site"
                    ),
                ),
            ],
            options={
                "verbose_name": "Redmine #488.1 Serum Crag Date Confirmation",
                "verbose_name_plural": "Redmine #488.1 Serum Crag Date Confirmations",
                "abstract": False,
            },
        ),
    ]
