# Generated by Django 4.2.11 on 2024-07-03 10:13

from django.db import migrations
from edc_qareports.utils import read_unmanaged_model_sql


class Migration(migrations.Migration):

    dependencies = [
        ("effect_reports", "0003_rm488serumcragdate"),
    ]

    operations = [
        migrations.RunSQL(
            read_unmanaged_model_sql(
                "rm488_serum_crag_date.sql",
                app_name="effect_reports",
            )
        ),
    ]
