# Generated by Django 4.2.11 on 2024-07-03 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("effect_reports", "0004_auto_20240703_1213"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rm488serumcragdate",
            options={
                "managed": False,
                "verbose_name": "Redmine #488.1: xxx",
                "verbose_name_plural": "Redmine #488.1: xxx",
            },
        ),
        migrations.AlterModelTable(
            name="rm488serumcragdate",
            table="rm488_serum_crag_date",
        ),
    ]
