# Generated by Django 4.2.11 on 2024-07-24 15:08

from django.db import migrations
from django.db.migrations import RunPython
from tqdm import tqdm

from effect_reports.models import ScreeningCragDateConfirmation


def initialise_screening_crag_date_confirmations(apps, schema_editor):
    model_cls = apps.get_model("effect_screening.subjectscreening")
    qs = model_cls.objects.all()
    total = qs.count()
    update_count = 0

    consent_model_cls = apps.get_model("effect_consent.subjectconsent")

    print(f"\nProcessing {total} Subject Screening instances ...")
    print(
        "Initialising ScreeningCragDateConfirmations for consented Subject Screening instances ..."
    )
    for screening_obj in tqdm(qs, total=total):
        if screening_obj.consented:  # TODO: and <= date
            consent_obj = consent_model_cls.objects.filter(
                screening_identifier=screening_obj.screening_identifier,
                subject_identifier=screening_obj.subject_identifier,
            ).first()

            screening_crag_date_confirmation = ScreeningCragDateConfirmation(
                report_datetime=screening_obj.eligibility_datetime,
                screening_identifier=screening_obj.screening_identifier,
                subject_identifier=screening_obj.subject_identifier,
                initials=screening_obj.initials,
                site_id=screening_obj.site.id,
                dob=consent_obj.dob,
                gender=screening_obj.gender,
                serum_crag_date=screening_obj.serum_crag_date,
                eligibility_datetime=screening_obj.eligibility_datetime,
                # TODO: ??? created, modified
                # TODO: ??? user_created/modified
                # TODO: ??? locale_created/modified
            )
            screening_crag_date_confirmation.save()
            update_count += 1

        # if not obj.safe_save_id:
        #     obj.safe_save_id = get_uuid()
        #     obj.modified = get_utcnow()
        #     obj.user_modified = __name__ if len(__name__) <= 50 else f"{__name__[:46]}..."
        #     obj.save(update_fields=["safe_save_id", "modified", "user_modified"])
    print(
        f"{update_count}/{total} consented Subject Screening consented instances updated xxx."
    )
    print("Done.")


class Migration(migrations.Migration):

    dependencies = [
        ("effect_reports", "0004_historicalscreeningcragdateconfirmation_and_more"),
    ]

    operations = [RunPython(initialise_screening_crag_date_confirmations)]
