# Generated by Django 5.1 on 2024-08-14 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("effect_reports", "0005_rename_consentedserumcragdate_serumcragdate_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rm792kwincurrentsxgteg3other",
            options={
                "default_permissions": ("view", "export", "viewallsites"),
                "managed": False,
                "verbose_name": "Redmine #792.2: Signs and Symptoms: Keyword in other G3 sx",
                "verbose_name_plural": "Redmine #792.2: Signs and Symptoms: Keyword in other G3 sx",
            },
        ),
        migrations.AlterModelOptions(
            name="rm792kwincurrentsxother",
            options={
                "default_permissions": ("view", "export", "viewallsites"),
                "managed": False,
                "verbose_name": "Redmine #792.1: Signs and Symptoms: Keyword in other sx",
                "verbose_name_plural": "Redmine #792.1: Signs and Symptoms: Keyword in other sx",
            },
        ),
        migrations.AlterModelOptions(
            name="rm792sisxlistcandidates",
            options={
                "default_permissions": ("view", "export", "viewallsites"),
                "managed": False,
                "verbose_name": "Redmine #792.3: Signs and Symptoms: Possible list candidates",
                "verbose_name_plural": "Redmine #792.3: Signs and Symptoms: Possible list candidates",
            },
        ),
    ]
