# Generated by Django 4.2.11 on 2024-08-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("effect_reports", "0005_feat_488_initialise_screening_crag_date_confirmation_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serumcragdateconfirmation",
            name="report_date",
        ),
    ]
