# Generated by Django 4.2.11 on 2024-08-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("effect_reports", "0006_remove_serumcragdateconfirmation_report_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SerumCragDateConfirmation",
            new_name="ConsentedSerumCragDate",
        ),
        migrations.AlterModelOptions(
            name="consentedserumcragdate",
            options={
                "verbose_name": "Redmine #488.1 Consented Serum Crag Date",
                "verbose_name_plural": "Redmine #488.1 Consented Serum Crag Dates",
            },
        ),
    ]
