# Generated by Django 4.2.11 on 2024-07-19 15:59

from django.db import migrations, models
import django_crypto_fields.fields.encrypted_char_field


class Migration(migrations.Migration):

    dependencies = [
        ("effect_reports", "0006_auto_20240703_1336"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rm488Consented",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("report_model", models.CharField(max_length=50)),
                ("subject_identifier", models.CharField(max_length=25)),
                ("created", models.DateTimeField()),
                ("screening_identifier", models.CharField(max_length=50)),
                (
                    "initials",
                    django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(
                        blank=True, help_text=" (Encryption: RSA local)", max_length=71
                    ),
                ),
                ("age_in_years", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("eligibility_date", models.DateField()),
                ("serum_crag_date", models.DateField()),
                ("days_difference", models.IntegerField()),
                ("user_created", models.CharField(max_length=25)),
                ("user_modified", models.CharField(max_length=25)),
            ],
            options={
                "verbose_name": "Redmine #488.1: xxx",
                "verbose_name_plural": "Redmine #488.1: xxx",
                "db_table": "rm488_serum_crag_date",
                "managed": False,
            },
        ),
    ]
