# Generated by Django 5.1.1 on 2024-09-13 11:43

from django.db import migrations
from edc_qareports.utils import read_unmanaged_model_sql


class Migration(migrations.Migration):

    dependencies = [
        ("effect_reports", "0006_auto_20240913_1115"),
    ]

    operations = [
        migrations.RunSQL("drop view if exists rm792_kw_in_current_sx_other"),
        migrations.RunSQL(
            read_unmanaged_model_sql(
                "rm792_kw_in_current_sx_other.sql",
                app_name="effect_reports",
            )
        ),
        migrations.RunSQL("drop view if exists rm792_kw_in_current_sx_gte_g3_other"),
        migrations.RunSQL(
            read_unmanaged_model_sql(
                "rm792_kw_in_current_sx_gte_g3_other.sql",
                app_name="effect_reports",
            )
        ),
        migrations.RunSQL("drop view if exists rm792_si_sx_list_candidates"),
        migrations.RunSQL(
            read_unmanaged_model_sql(
                "rm792_si_sx_list_candidates.sql",
                app_name="effect_reports",
            )
        ),
    ]
