# Generated by Django 4.2.11 on 2024-07-23 09:26


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("effect_reports", "0008_auto_20240719_1800"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rm488consented",
            options={
                "managed": False,
                "verbose_name": "Redmine #488.1: Consented (Serum Crag Date Confirmation",
                "verbose_name_plural": "Redmine #488.1: Consented (Serum Crag Date Confirmation",
            },
        ),
        migrations.AlterModelOptions(
            name="rm488serumcragdate",
            options={
                "managed": False,
                "verbose_name": "Redmine #488.2: Serum Grag Date (orig WIP)",
                "verbose_name_plural": "Redmine #488.2: xxx (orig WIP)",
            },
        ),
    ]
