# Generated by Django 4.2.11 on 2024-07-31 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "effect_reports",
            "0012_alter_screeningcragdateconfirmation_confirmed_serum_crag_date_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalCragDateConfirmation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("report_model", models.CharField(max_length=50)),
                ("subject_identifier", models.CharField(max_length=25)),
                ("created", models.DateTimeField()),
                (
                    "screening_identifier",
                    models.CharField(max_length=50, null=True, verbose_name="Screening ID"),
                ),
                ("report_date", models.DateField(null=True)),
                ("serum_crag_date", models.DateField(null=True)),
                (
                    "serum_crag_value",
                    models.CharField(max_length=50, null=True, verbose_name="CrAg"),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Screening Crag Date Confirmation",
                "verbose_name_plural": "historical Screening Crag Date Confirmations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="CragDateConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("report_model", models.CharField(max_length=50)),
                ("subject_identifier", models.CharField(max_length=25)),
                ("created", models.DateTimeField()),
                (
                    "screening_identifier",
                    models.CharField(max_length=50, null=True, verbose_name="Screening ID"),
                ),
                ("report_date", models.DateField(null=True)),
                ("serum_crag_date", models.DateField(null=True)),
                (
                    "serum_crag_value",
                    models.CharField(max_length=50, null=True, verbose_name="CrAg"),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sites.site"
                    ),
                ),
            ],
            options={
                "verbose_name": "Screening Crag Date Confirmation",
                "verbose_name_plural": "Screening Crag Date Confirmations",
                "abstract": False,
            },
        ),
    ]
