# Generated by Django 4.2.11 on 2024-07-31 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("effect_reports", "0014_alter_cragdateconfirmation_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cragdateconfirmation",
            old_name="eligiblility_date",
            new_name="eligibility_date",
        ),
    ]
