# Generated by Django 3.2.8 on 2022-04-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_ae", "0003_auto_20220322_2029"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aelocalreview",
            name="original_report_agreed",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                help_text="If NO, explain in the narrative below",
                max_length=15,
                null=True,
                verbose_name="Does this Clinical Reviewer agree with the original AE report?",
            ),
        ),
        migrations.AlterField(
            model_name="aesponsorreview",
            name="original_report_agreed",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                help_text="If NO, explain in the narrative below",
                max_length=15,
                null=True,
                verbose_name="Does this Clinical Reviewer agree with the original AE report?",
            ),
        ),
    ]
