# Generated by Django 3.2 on 2022-08-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("effect_ae", "0009_auto_20220824_1919"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aeinitial",
            name="patient_admitted",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Was the participant admitted?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalaeinitial",
            name="patient_admitted",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Was the participant admitted?",
            ),
        ),
    ]
