# Generated by Django 4.2.6 on 2023-11-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("effect_ae", "0018_alter_deathreport_blurred_vision_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deathreport",
            name="clinical_notes_available",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                help_text="If YES, include details of admission in narrative",
                max_length=15,
                verbose_name="If died as inpatient, are clinical notes available to study staff?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldeathreport",
            name="clinical_notes_available",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                help_text="If YES, include details of admission in narrative",
                max_length=15,
                verbose_name="If died as inpatient, are clinical notes available to study staff?",
            ),
        ),
    ]
