# Generated by Django 5.2.6 on 2025-09-18 00:24

import django.utils.timezone
import edc_model.validators.date
import edc_protocol.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_ae", "0024_alter_aefollowup_action_identifier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aefollowup",
            name="report_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Report date and time"
            ),
        ),
        migrations.AlterField(
            model_name="aeinitial",
            name="ae_awareness_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                validators=[edc_model.validators.date.date_not_future],
                verbose_name="AE Awareness date",
            ),
        ),
        migrations.AlterField(
            model_name="aeinitial",
            name="ae_start_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                validators=[edc_model.validators.date.date_not_future],
                verbose_name="Actual Start Date of AE",
            ),
        ),
        migrations.AlterField(
            model_name="aeinitial",
            name="report_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Report Date and Time"
            ),
        ),
        migrations.AlterField(
            model_name="aesusar",
            name="report_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                validators=[edc_model.validators.date.datetime_not_future],
                verbose_name="Report date and time",
            ),
        ),
        migrations.AlterField(
            model_name="aetmg",
            name="report_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                validators=[edc_model.validators.date.datetime_not_future],
                verbose_name="Report date and time",
            ),
        ),
        migrations.AlterField(
            model_name="deathreport",
            name="report_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                validators=[
                    edc_protocol.validators.datetime_not_before_study_start,
                    edc_model.validators.date.datetime_not_future,
                ],
                verbose_name="Report Date",
            ),
        ),
        migrations.AlterField(
            model_name="deathreporttmg",
            name="report_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                validators=[
                    edc_protocol.validators.datetime_not_before_study_start,
                    edc_model.validators.date.datetime_not_future,
                ],
                verbose_name="Report Date",
            ),
        ),
        migrations.AlterField(
            model_name="historicalaefollowup",
            name="report_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Report date and time"
            ),
        ),
        migrations.AlterField(
            model_name="historicalaeinitial",
            name="ae_awareness_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                validators=[edc_model.validators.date.date_not_future],
                verbose_name="AE Awareness date",
            ),
        ),
        migrations.AlterField(
            model_name="historicalaeinitial",
            name="ae_start_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                validators=[edc_model.validators.date.date_not_future],
                verbose_name="Actual Start Date of AE",
            ),
        ),
        migrations.AlterField(
            model_name="historicalaeinitial",
            name="report_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Report Date and Time"
            ),
        ),
        migrations.AlterField(
            model_name="historicalaesusar",
            name="report_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                validators=[edc_model.validators.date.datetime_not_future],
                verbose_name="Report date and time",
            ),
        ),
        migrations.AlterField(
            model_name="historicalaetmg",
            name="report_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                validators=[edc_model.validators.date.datetime_not_future],
                verbose_name="Report date and time",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldeathreport",
            name="report_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                validators=[
                    edc_protocol.validators.datetime_not_before_study_start,
                    edc_model.validators.date.datetime_not_future,
                ],
                verbose_name="Report Date",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldeathreporttmg",
            name="report_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                validators=[
                    edc_protocol.validators.datetime_not_before_study_start,
                    edc_model.validators.date.datetime_not_future,
                ],
                verbose_name="Report Date",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldeathreporttmgsecond",
            name="report_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                validators=[
                    edc_protocol.validators.datetime_not_before_study_start,
                    edc_model.validators.date.datetime_not_future,
                ],
                verbose_name="Report Date",
            ),
        ),
    ]
