# Generated by Django 5.2.7 on 2025-10-08 07:33

import django.utils.timezone
import edc_model.validators.date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "effect_ae",
            "0027_alter_aefollowup_revision_alter_aeinitial_revision_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="aelocalreview",
            name="report_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                validators=[edc_model.validators.date.datetime_not_future],
                verbose_name="Report date and time",
            ),
        ),
        migrations.AlterField(
            model_name="aesponsorreview",
            name="report_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                validators=[edc_model.validators.date.datetime_not_future],
                verbose_name="Report date and time",
            ),
        ),
    ]
