# Generated by Django 5.2.10 on 2026-04-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_ae", "0028_alter_aelocalreview_report_datetime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deathreporttmg",
            name="cryptococcal_relatedness",
            field=models.CharField(
                choices=[
                    ("not_related", "Not related"),
                    ("unlikely_related", "Unlikely related"),
                    ("possibly_related", "Possibly related"),
                    ("probably_related", "Probably related"),
                    ("definitely_related", "Definitely related"),
                    ("N/A", "Not applicable"),
                    ("not_evaluated", "Not evaluated"),
                ],
                default="not_evaluated",
                max_length=25,
                verbose_name="Relationship of death to cryptococcal infection:",
            ),
        ),
        migrations.AddField(
            model_name="historicaldeathreporttmg",
            name="cryptococcal_relatedness",
            field=models.CharField(
                choices=[
                    ("not_related", "Not related"),
                    ("unlikely_related", "Unlikely related"),
                    ("possibly_related", "Possibly related"),
                    ("probably_related", "Probably related"),
                    ("definitely_related", "Definitely related"),
                    ("N/A", "Not applicable"),
                    ("not_evaluated", "Not evaluated"),
                ],
                default="not_evaluated",
                max_length=25,
                verbose_name="Relationship of death to cryptococcal infection:",
            ),
        ),
        migrations.AddField(
            model_name="historicaldeathreporttmgsecond",
            name="cryptococcal_relatedness",
            field=models.CharField(
                choices=[
                    ("not_related", "Not related"),
                    ("unlikely_related", "Unlikely related"),
                    ("possibly_related", "Possibly related"),
                    ("probably_related", "Probably related"),
                    ("definitely_related", "Definitely related"),
                    ("N/A", "Not applicable"),
                    ("not_evaluated", "Not evaluated"),
                ],
                default="not_evaluated",
                max_length=25,
                verbose_name="Relationship of death to cryptococcal infection:",
            ),
        ),
    ]
