# Generated by Django 5.2.10 on 2026-04-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_ae", "0029_deathreporttmg_cryptococcal_relatedness_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deathreporttmg",
            name="cryptococcal_relatedness_comment",
            field=models.TextField(blank=True, default="", max_length=250),
        ),
        migrations.AddField(
            model_name="historicaldeathreporttmg",
            name="cryptococcal_relatedness_comment",
            field=models.TextField(blank=True, default="", max_length=250),
        ),
        migrations.AddField(
            model_name="historicaldeathreporttmgsecond",
            name="cryptococcal_relatedness_comment",
            field=models.TextField(blank=True, default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="deathreporttmg",
            name="cryptococcal_relatedness",
            field=models.CharField(
                choices=[
                    ("not_related", "Not related"),
                    ("unlikely_related", "Unlikely related"),
                    ("possibly_related", "Possibly related"),
                    ("probably_related", "Probably related"),
                    ("definitely_related", "Definitely related"),
                    ("not_evaluated", "Not evaluated"),
                ],
                default="not_evaluated",
                max_length=25,
                verbose_name="In your opinion, is the cause death related to cryptococcal infection?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldeathreporttmg",
            name="cryptococcal_relatedness",
            field=models.CharField(
                choices=[
                    ("not_related", "Not related"),
                    ("unlikely_related", "Unlikely related"),
                    ("possibly_related", "Possibly related"),
                    ("probably_related", "Probably related"),
                    ("definitely_related", "Definitely related"),
                    ("not_evaluated", "Not evaluated"),
                ],
                default="not_evaluated",
                max_length=25,
                verbose_name="In your opinion, is the cause death related to cryptococcal infection?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldeathreporttmgsecond",
            name="cryptococcal_relatedness",
            field=models.CharField(
                choices=[
                    ("not_related", "Not related"),
                    ("unlikely_related", "Unlikely related"),
                    ("possibly_related", "Possibly related"),
                    ("probably_related", "Probably related"),
                    ("definitely_related", "Definitely related"),
                    ("not_evaluated", "Not evaluated"),
                ],
                default="not_evaluated",
                max_length=25,
                verbose_name="In your opinion, is the cause death related to cryptococcal infection?",
            ),
        ),
    ]
