# Generated by Django 6.0.4 on 2026-04-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_ae", "0031_aefinalclassification"),
    ]

    operations = [
        migrations.AddField(
            model_name="aefinalclassification",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
