# Generated by Django 6.0.4 on 2026-04-22 01:52

import _socket
import django.db.models.deletion
import django.utils.timezone
import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
import django_audit_fields.fields.uuid_auto_field
import django_revision.revision_field
import edc_model_fields.fields.other_charfield
import edc_sites.managers
import effect_ae.models.death_final_cause
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_adverse_event", "0018_alter_aeactionclassification_options_and_more"),
        ("effect_ae", "0033_alter_aefinalclassification_managers_and_more"),
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalDeathFinalCause",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="System field. From git repository (tag:branch:commit), project metadata, project toml, project VERSION, or settings.",
                        max_length=75,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        default="",
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        default="",
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        default="",
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Device created",
                    ),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Device modified",
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                    ),
                ),
                ("subject_identifier", models.CharField(max_length=50)),
                (
                    "subject_identifier_as_pk",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    "subject_identifier_aka",
                    models.CharField(
                        default="",
                        editable=False,
                        help_text="track a previously allocated identifier.",
                        max_length=50,
                        verbose_name="Subject Identifier a.k.a",
                    ),
                ),
                (
                    "report_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "final_cause_of_death_other",
                    edc_model_fields.fields.other_charfield.OtherCharField(
                        blank=True,
                        default="",
                        max_length=250,
                        verbose_name="If other, please specify ...",
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                (
                    "death_report_action_identifier",
                    models.CharField(db_index=True, max_length=25),
                ),
                (
                    "cause_of_death_other",
                    edc_model_fields.fields.other_charfield.OtherCharField(
                        blank=True,
                        default="",
                        help_text="Copied from original Death report",
                        max_length=250,
                        verbose_name="Original cause of death (Other)",
                    ),
                ),
                (
                    "tmg_one_action_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=25, null=True
                    ),
                ),
                (
                    "tmg_one_cause_of_death_other",
                    edc_model_fields.fields.other_charfield.OtherCharField(
                        blank=True,
                        default="",
                        help_text="Copied from the Death Report TMG (1)",
                        max_length=250,
                        verbose_name="Investigator cause of death (Other)",
                    ),
                ),
                (
                    "tmg_two_action_identifier",
                    models.CharField(
                        blank=True, db_index=True, max_length=25, null=True
                    ),
                ),
                (
                    "tmg_two_cause_of_death_other",
                    edc_model_fields.fields.other_charfield.OtherCharField(
                        blank=True,
                        default="",
                        help_text="Copied from the Death Report TMG (2)",
                        max_length=250,
                        verbose_name="Investigator cause of death (Other)",
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "cause_of_death",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Copied from original Death report",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="edc_adverse_event.causeofdeath",
                        verbose_name="Original cause of death",
                    ),
                ),
                (
                    "death_report",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="effect_ae.deathreport",
                    ),
                ),
                (
                    "final_cause_of_death",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="edc_adverse_event.causeofdeath",
                        verbose_name="Cause of death",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sites.site",
                    ),
                ),
                (
                    "tmg_one",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="May be null if no Death Report TMG report has been submitted yet.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="effect_ae.deathreporttmg",
                    ),
                ),
                (
                    "tmg_one_cause_of_death",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Copied from the Death Report TMG (1)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="edc_adverse_event.causeofdeath",
                        verbose_name="Investigator cause of death",
                    ),
                ),
                (
                    "tmg_two",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="May be null if no Death Report TMG (Second) report has been submitted yet.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="effect_ae.deathreporttmgsecond",
                    ),
                ),
                (
                    "tmg_two_cause_of_death",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Copied from the Death Report TMG (2)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="edc_adverse_event.causeofdeath",
                        verbose_name="Investigator cause of death",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Final cause of death",
                "verbose_name_plural": "historical Final cause of death",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="DeathFinalCause",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="System field. From git repository (tag:branch:commit), project metadata, project toml, project VERSION, or settings.",
                        max_length=75,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        default="",
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        default="",
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        default="",
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Device created",
                    ),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Device modified",
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject_identifier", models.CharField(max_length=50)),
                (
                    "subject_identifier_as_pk",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    "subject_identifier_aka",
                    models.CharField(
                        default="",
                        editable=False,
                        help_text="track a previously allocated identifier.",
                        max_length=50,
                        verbose_name="Subject Identifier a.k.a",
                    ),
                ),
                (
                    "report_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "final_cause_of_death_other",
                    edc_model_fields.fields.other_charfield.OtherCharField(
                        blank=True,
                        default="",
                        max_length=250,
                        verbose_name="If other, please specify ...",
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                (
                    "death_report_action_identifier",
                    models.CharField(max_length=25, unique=True),
                ),
                (
                    "cause_of_death_other",
                    edc_model_fields.fields.other_charfield.OtherCharField(
                        blank=True,
                        default="",
                        help_text="Copied from original Death report",
                        max_length=250,
                        verbose_name="Original cause of death (Other)",
                    ),
                ),
                (
                    "tmg_one_action_identifier",
                    models.CharField(blank=True, max_length=25, null=True, unique=True),
                ),
                (
                    "tmg_one_cause_of_death_other",
                    edc_model_fields.fields.other_charfield.OtherCharField(
                        blank=True,
                        default="",
                        help_text="Copied from the Death Report TMG (1)",
                        max_length=250,
                        verbose_name="Investigator cause of death (Other)",
                    ),
                ),
                (
                    "tmg_two_action_identifier",
                    models.CharField(blank=True, max_length=25, null=True, unique=True),
                ),
                (
                    "tmg_two_cause_of_death_other",
                    edc_model_fields.fields.other_charfield.OtherCharField(
                        blank=True,
                        default="",
                        help_text="Copied from the Death Report TMG (2)",
                        max_length=250,
                        verbose_name="Investigator cause of death (Other)",
                    ),
                ),
                (
                    "cause_of_death",
                    models.ForeignKey(
                        help_text="Copied from original Death report",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="edc_adverse_event.causeofdeath",
                        verbose_name="Original cause of death",
                    ),
                ),
                (
                    "death_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="effect_ae.deathreport",
                    ),
                ),
                (
                    "final_cause_of_death",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="edc_adverse_event.causeofdeath",
                        verbose_name="Cause of death",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sites.site",
                    ),
                ),
                (
                    "tmg_one",
                    models.ForeignKey(
                        blank=True,
                        help_text="May be null if no Death Report TMG report has been submitted yet.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="effect_ae.deathreporttmg",
                    ),
                ),
                (
                    "tmg_one_cause_of_death",
                    models.ForeignKey(
                        help_text="Copied from the Death Report TMG (1)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="edc_adverse_event.causeofdeath",
                        verbose_name="Investigator cause of death",
                    ),
                ),
                (
                    "tmg_two",
                    models.ForeignKey(
                        blank=True,
                        help_text="May be null if no Death Report TMG (Second) report has been submitted yet.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="effect_ae.deathreporttmgsecond",
                    ),
                ),
                (
                    "tmg_two_cause_of_death",
                    models.ForeignKey(
                        help_text="Copied from the Death Report TMG (2)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="edc_adverse_event.causeofdeath",
                        verbose_name="Investigator cause of death",
                    ),
                ),
            ],
            options={
                "verbose_name": "Final cause of death",
                "verbose_name_plural": "Final cause of death",
                "abstract": False,
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["modified", "created"],
                        name="effect_ae_d_modifie_0229e9_idx",
                    ),
                    models.Index(
                        fields=["user_modified", "user_created"],
                        name="effect_ae_d_user_mo_66713d_idx",
                    ),
                ],
            },
            managers=[
                ("objects", effect_ae.models.death_final_cause.ModelManager()),
                ("on_site", edc_sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
