# Generated by Django 6.0.4 on 2026-04-22 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_adverse_event", "0018_alter_aeactionclassification_options_and_more"),
        ("effect_ae", "0034_historicaldeathfinalcause_deathfinalcause"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deathfinalcause",
            name="final_cause_of_death",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="edc_adverse_event.causeofdeath",
                verbose_name="Final cause of death",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldeathfinalcause",
            name="final_cause_of_death",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_adverse_event.causeofdeath",
                verbose_name="Final cause of death",
            ),
        ),
    ]
