# Generated by Django 6.0.4 on 2026-04-22 02:36

import django.db.models.deletion
import edc_model_fields.fields.other_charfield
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_adverse_event", "0018_alter_aeactionclassification_options_and_more"),
        ("effect_ae", "0035_alter_deathfinalcause_final_cause_of_death_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deathfinalcause",
            options={
                "default_manager_name": "objects",
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Death: Final cause of death",
                "verbose_name_plural": "Death: Final cause of death",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldeathfinalcause",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Death: Final cause of death",
                "verbose_name_plural": "historical Death: Final cause of death",
            },
        ),
        migrations.AddField(
            model_name="deathfinalcause",
            name="tmg_one_agrees",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="",
                max_length=15,
                verbose_name="TMG investigator one agrees with cause of death from the original death report?",
            ),
        ),
        migrations.AddField(
            model_name="deathfinalcause",
            name="tmg_two_agrees",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="",
                max_length=15,
                verbose_name="TMG investigator two agrees with cause of death from the original death report?",
            ),
        ),
        migrations.AddField(
            model_name="historicaldeathfinalcause",
            name="tmg_one_agrees",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="",
                max_length=15,
                verbose_name="TMG investigator one agrees with cause of death from the original death report?",
            ),
        ),
        migrations.AddField(
            model_name="historicaldeathfinalcause",
            name="tmg_two_agrees",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="",
                max_length=15,
                verbose_name="TMG investigator two agrees with cause of death from the original death report?",
            ),
        ),
        migrations.AlterField(
            model_name="deathfinalcause",
            name="tmg_one_cause_of_death",
            field=models.ForeignKey(
                help_text="Copied from the Death Report TMG (1)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="edc_adverse_event.causeofdeath",
                verbose_name="Investigator 1 cause of death",
            ),
        ),
        migrations.AlterField(
            model_name="deathfinalcause",
            name="tmg_one_cause_of_death_other",
            field=edc_model_fields.fields.other_charfield.OtherCharField(
                blank=True,
                default="",
                help_text="Copied from the Death Report TMG (1)",
                max_length=250,
                verbose_name="Investigator 1 cause of death (Other)",
            ),
        ),
        migrations.AlterField(
            model_name="deathfinalcause",
            name="tmg_two_cause_of_death",
            field=models.ForeignKey(
                help_text="Copied from the Death Report TMG (2)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="edc_adverse_event.causeofdeath",
                verbose_name="Investigator 2 cause of death",
            ),
        ),
        migrations.AlterField(
            model_name="deathfinalcause",
            name="tmg_two_cause_of_death_other",
            field=edc_model_fields.fields.other_charfield.OtherCharField(
                blank=True,
                default="",
                help_text="Copied from the Death Report TMG (2)",
                max_length=250,
                verbose_name="Investigator 2 cause of death (Other)",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldeathfinalcause",
            name="tmg_one_cause_of_death",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Copied from the Death Report TMG (1)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_adverse_event.causeofdeath",
                verbose_name="Investigator 1 cause of death",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldeathfinalcause",
            name="tmg_one_cause_of_death_other",
            field=edc_model_fields.fields.other_charfield.OtherCharField(
                blank=True,
                default="",
                help_text="Copied from the Death Report TMG (1)",
                max_length=250,
                verbose_name="Investigator 1 cause of death (Other)",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldeathfinalcause",
            name="tmg_two_cause_of_death",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Copied from the Death Report TMG (2)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_adverse_event.causeofdeath",
                verbose_name="Investigator 2 cause of death",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldeathfinalcause",
            name="tmg_two_cause_of_death_other",
            field=edc_model_fields.fields.other_charfield.OtherCharField(
                blank=True,
                default="",
                help_text="Copied from the Death Report TMG (2)",
                max_length=250,
                verbose_name="Investigator 2 cause of death (Other)",
            ),
        ),
    ]
