# Generated by Django 6.0.4 on 2026-04-22 19:30

import edc_action_item.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("effect_ae", "0037_delete_deathreporttmgsecond_deathreporttmgsecond_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="deathreporttmgsecond",
            managers=[
                ("objects", edc_action_item.managers.ActionIdentifierModelManager()),
                ("on_site", edc_action_item.managers.ActionIdentifierSiteManager()),
            ],
        ),
    ]
