# Generated by Django 6.0.4 on 2026-05-07 23:04

import edc_action_item.managers
import effect_ae.models.death_report_tmg_second
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("effect_ae", "0038_alter_deathreporttmgsecond_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="deathreporttmgsecond",
            managers=[
                (
                    "objects",
                    effect_ae.models.death_report_tmg_second.DeathReportTmgSecondManager(),
                ),
                ("on_site", edc_action_item.managers.ActionIdentifierSiteManager()),
            ],
        ),
    ]
