# Generated by Django 6.0.5 on 2026-06-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_ae", "0039_alter_deathreporttmgsecond_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="deathfinalcause",
            name="cryptococcal_relatedness",
            field=models.CharField(
                choices=[
                    ("not_related", "Not related"),
                    ("unlikely_related", "Unlikely related"),
                    ("possibly_related", "Possibly related"),
                    ("probably_related", "Probably related"),
                    ("definitely_related", "Definitely related"),
                    ("not_evaluated", "Not evaluated"),
                ],
                default="not_evaluated",
                max_length=25,
                verbose_name="In your opinion, is the cause death related to cryptococcal infection?",
            ),
        ),
        migrations.AddField(
            model_name="historicaldeathfinalcause",
            name="cryptococcal_relatedness",
            field=models.CharField(
                choices=[
                    ("not_related", "Not related"),
                    ("unlikely_related", "Unlikely related"),
                    ("possibly_related", "Possibly related"),
                    ("probably_related", "Probably related"),
                    ("definitely_related", "Definitely related"),
                    ("not_evaluated", "Not evaluated"),
                ],
                default="not_evaluated",
                max_length=25,
                verbose_name="In your opinion, is the cause death related to cryptococcal infection?",
            ),
        ),
    ]
