# Generated by Django 3.2.9 on 2021-11-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_screening", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subjectrefusal",
            name="site",
        ),
        migrations.RemoveField(
            model_name="subjectrefusal",
            name="subject_screening",
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="contraindicated_meds",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("not_answered", "Not answered")],
                default="not_answered",
                max_length=25,
                verbose_name="Is the patient taking any contraindicated concomitant medications?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="on_fluconazole",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("not_answered", "Not answered")],
                default="not_answered",
                help_text="fluconazole @ (800-1200 mg/day) for ≥1 week",
                max_length=25,
                verbose_name="Is the patent already taking high-dose fluconazole treatment?",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="contraindicated_meds",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("not_answered", "Not answered")],
                default="not_answered",
                max_length=25,
                verbose_name="Is the patient taking any contraindicated concomitant medications?",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="on_fluconazole",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("not_answered", "Not answered")],
                default="not_answered",
                help_text="fluconazole @ (800-1200 mg/day) for ≥1 week",
                max_length=25,
                verbose_name="Is the patent already taking high-dose fluconazole treatment?",
            ),
        ),
        migrations.DeleteModel(
            name="HistoricalSubjectRefusal",
        ),
        migrations.DeleteModel(
            name="SubjectRefusal",
        ),
    ]
