# Generated by Django 3.2.9 on 2021-11-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_screening", "0002_auto_20211118_2138"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsubjectscreening",
            name="real_eligibility_datetime",
            field=models.DateTimeField(
                editable=False,
                help_text="Date and time eligibility was determined relative to now",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subjectscreening",
            name="real_eligibility_datetime",
            field=models.DateTimeField(
                editable=False,
                help_text="Date and time eligibility was determined relative to now",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="eligibility_datetime",
            field=models.DateTimeField(
                editable=False,
                help_text="Date and time eligibility was determined relative to report_datetime",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="eligibility_datetime",
            field=models.DateTimeField(
                editable=False,
                help_text="Date and time eligibility was determined relative to report_datetime",
                null=True,
            ),
        ),
    ]
