# Generated by Django 3.2.9 on 2021-11-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("effect_screening", "0007_auto_20211119_2118"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="csf_cm_evidence",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("PENDING", "Pending results"),
                    ("not_tested", "Additional testing not done"),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                help_text="At any time between the CrAg test and screening for eligibility. <BR>If results on tests on CSF are `pending`, report on DAY 1 / baseline visit or when available.",
                max_length=25,
                verbose_name="Any other evidence of CM on CSF?",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="csf_cm_evidence",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("PENDING", "Pending results"),
                    ("not_tested", "Additional testing not done"),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                help_text="At any time between the CrAg test and screening for eligibility. <BR>If results on tests on CSF are `pending`, report on DAY 1 / baseline visit or when available.",
                max_length=25,
                verbose_name="Any other evidence of CM on CSF?",
            ),
        ),
    ]
