# Generated by Django 3.2.11 on 2022-03-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_screening", "0010_auto_20220329_1743"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="cm_on_csf",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("PENDING", "Pending results"),
                    ("not_tested", "Additional testing not done"),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                help_text="At any time between the CrAg test and screening for eligibility. <BR>If results on tests on CSF are `pending`, report on DAY 1 / baseline visit or when available.",
                max_length=25,
                verbose_name="Was CM confirmed in CSF by any other method?",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="cm_on_csf",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("PENDING", "Pending results"),
                    ("not_tested", "Additional testing not done"),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                help_text="At any time between the CrAg test and screening for eligibility. <BR>If results on tests on CSF are `pending`, report on DAY 1 / baseline visit or when available.",
                max_length=25,
                verbose_name="Was CM confirmed in CSF by any other method?",
            ),
        ),
    ]
