# Generated by Django 3.2.11 on 2022-03-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_screening", "0014_auto_20220330_1707"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsubjectscreening",
            name="pregnant_or_bf",
        ),
        migrations.RemoveField(
            model_name="subjectscreening",
            name="pregnant_or_bf",
        ),
        migrations.AddField(
            model_name="historicalsubjectscreening",
            name="breast_feeding",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Is the patient breasfeeding?",
            ),
        ),
        migrations.AddField(
            model_name="historicalsubjectscreening",
            name="preg_test_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Pregnancy test date (Urine or serum βhCG)"
            ),
        ),
        migrations.AddField(
            model_name="historicalsubjectscreening",
            name="pregnant",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("N/A", "Not Applicable: e.g. male or post-menopausal"),
                ],
                default="N/A",
                max_length=15,
                verbose_name="Is the patient pregnant?",
            ),
        ),
        migrations.AddField(
            model_name="subjectscreening",
            name="breast_feeding",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Is the patient breasfeeding?",
            ),
        ),
        migrations.AddField(
            model_name="subjectscreening",
            name="preg_test_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Pregnancy test date (Urine or serum βhCG)"
            ),
        ),
        migrations.AddField(
            model_name="subjectscreening",
            name="pregnant",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("N/A", "Not Applicable: e.g. male or post-menopausal"),
                ],
                default="N/A",
                max_length=15,
                verbose_name="Is the patient pregnant?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="mg_ssx_other",
            field=models.TextField(
                blank=True,
                help_text="If more than one, please separate each with a comma (,).",
                null=True,
                verbose_name="If 'Other' SSX, please specify",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="mg_ssx_since_crag",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("not_answered", "Not answered")],
                default="not_answered",
                max_length=25,
                verbose_name="Has the patient had clinical signs/symptoms of symptomatic meningitis at any time since CrAg screening?",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="mg_ssx_other",
            field=models.TextField(
                blank=True,
                help_text="If more than one, please separate each with a comma (,).",
                null=True,
                verbose_name="If 'Other' SSX, please specify",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="mg_ssx_since_crag",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("not_answered", "Not answered")],
                default="not_answered",
                max_length=25,
                verbose_name="Has the patient had clinical signs/symptoms of symptomatic meningitis at any time since CrAg screening?",
            ),
        ),
    ]
