# Generated by Django 3.2.8 on 2022-05-16 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("effect_screening", "0020_auto_20220419_2126"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalsubjectscreening",
            old_name="on_fluconazole",
            new_name="on_flucon",
        ),
        migrations.RenameField(
            model_name="subjectscreening",
            old_name="on_fluconazole",
            new_name="on_flucon",
        ),
    ]
