# Generated by Django 3.2.16 on 2022-10-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_screening", "0026_auto_20220915_1612"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="csf_crag_value",
            field=models.CharField(
                choices=[
                    ("POS", "Positive"),
                    ("NEG", "Negative"),
                    ("PENDING", "Pending"),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                max_length=15,
                verbose_name="CSF CrAg result",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="csf_crag_value",
            field=models.CharField(
                choices=[
                    ("POS", "Positive"),
                    ("NEG", "Negative"),
                    ("PENDING", "Pending"),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                max_length=15,
                verbose_name="CSF CrAg result",
            ),
        ),
    ]
