# Generated by Django 4.2.11 on 2024-03-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_screening", "0036_alter_subjectscreening_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsubjectscreening",
            name="safe_save_id",
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="subjectscreening",
            name="safe_save_id",
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
