# Generated by Django 4.2.11 on 2024-05-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "effect_screening",
            "0045_alter_historicalsubjectscreening_unsuitable_reason_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsubjectscreening",
            name="parent_guardian_consent",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                help_text="( if 'No', STOP )",
                max_length=25,
                verbose_name="If patient is under 18, do you have consent from the parent or legal guardian to capture this information?",
            ),
        ),
        migrations.AddField(
            model_name="subjectscreening",
            name="parent_guardian_consent",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                help_text="( if 'No', STOP )",
                max_length=25,
                verbose_name="If patient is under 18, do you have consent from the parent or legal guardian to capture this information?",
            ),
        ),
    ]
