# Generated by Django 4.2.11 on 2024-08-01 15:31

from django.db import migrations, models
import edc_model.validators.date


class Migration(migrations.Migration):

    dependencies = [
        ("effect_screening", "0049_re_assess_serum_crag_date_elig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="serum_crag_date",
            field=models.DateField(
                help_text="Test must have been performed within the last 21 days.",
                null=True,
                validators=[edc_model.validators.date.date_not_future],
                verbose_name="Serum/plasma CrAg sample collection date",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="serum_crag_date",
            field=models.DateField(
                help_text="Test must have been performed within the last 21 days.",
                null=True,
                validators=[edc_model.validators.date.date_not_future],
                verbose_name="Serum/plasma CrAg sample collection date",
            ),
        ),
    ]
