# Generated by Django 3.2.8 on 2022-02-15 14:59

from django.db import migrations
from django.db.migrations import RunPython
from edc_action_item.utils import update_action_identifier

from effect_subject.action_items import FollowupAction, SxAction


def update_followup_action_identifier(apps, schema_editor):
    update_action_identifier(
        model="effect_subject.followup",
        action_cls=FollowupAction,
        apps=apps,
    )


def update_sx_action_identifier(apps, schema_editor):
    update_action_identifier(
        model="effect_subject.signsandsymptoms",
        action_cls=SxAction,
        apps=apps,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("effect_subject", "0006_auto_20220215_1649"),
    ]

    operations = [
        RunPython(
            update_followup_action_identifier,
            hints={"target_db": "default"},
        ),
        RunPython(
            update_sx_action_identifier,
            hints={"target_db": "default"},
        ),
    ]
