# Generated by Django 3.2.8 on 2022-02-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effect_subject', '0007_auto_20220216_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmentalstatus',
            name='modified_rankin_score',
            field=models.CharField(choices=[('0', 'No symptoms'), ('1', 'No significant disability. Able to carry out usual activities, despite some symptoms.'), ('2', 'Slight disability. Able to look after own affairs without assistance, but unable to carry out all previous activities.'), ('3', 'Moderate disability. Requires some help, but able to walk unassisted.'), ('4', 'Moderately severe disability. Unable to attend to own bodily needs without assistance, and unable to walk unassisted.'), ('5', 'Severe disability. Requires constant nursing care and attention, bedridden, incontinent.'), ('6', 'Dead'), ('not_done', 'Not done')], max_length=15, verbose_name='Modified Rankin Score?'),
        ),
        migrations.AlterField(
            model_name='mentalstatus',
            name='modified_rankin_score',
            field=models.CharField(choices=[('0', 'No symptoms'), ('1', 'No significant disability. Able to carry out usual activities, despite some symptoms.'), ('2', 'Slight disability. Able to look after own affairs without assistance, but unable to carry out all previous activities.'), ('3', 'Moderate disability. Requires some help, but able to walk unassisted.'), ('4', 'Moderately severe disability. Unable to attend to own bodily needs without assistance, and unable to walk unassisted.'), ('5', 'Severe disability. Requires constant nursing care and attention, bedridden, incontinent.'), ('6', 'Dead'), ('not_done', 'Not done')], max_length=15, verbose_name='Modified Rankin Score?'),
        ),
    ]
