# Generated by Django 3.2.8 on 2022-02-18 20:45

from django.db import migrations, models
import edc_model.models.fields.other_charfield


class Migration(migrations.Migration):

    dependencies = [
        ('effect_subject', '0008_auto_20220216_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='assessment_type_other',
            field=edc_model.models.fields.other_charfield.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If other, please specify ...'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='assessment_type_other',
            field=edc_model.models.fields.other_charfield.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If other, please specify ...'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='assessment_type',
            field=models.CharField(choices=[('telephone', 'Telephone'), ('in_person', 'In person'), ('OTHER', 'Other, please specify below ...')], max_length=15, verbose_name='Was this a telephone follow up or an in person visit?'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='info_source',
            field=models.CharField(choices=[('patient', 'Patient'), ('next_of_kin', 'Next of kin'), ('OTHER', 'Other'), ('N/A', 'Not applicable (if not telephone follow-up)')], default='patient', max_length=15, verbose_name='If by telephone, who did you speak to?'),
        ),
        migrations.AlterField(
            model_name='historicalfollowup',
            name='assessment_type',
            field=models.CharField(choices=[('telephone', 'Telephone'), ('in_person', 'In person'), ('OTHER', 'Other, please specify below ...')], max_length=15, verbose_name='Was this a telephone follow up or an in person visit?'),
        ),
        migrations.AlterField(
            model_name='historicalfollowup',
            name='info_source',
            field=models.CharField(choices=[('patient', 'Patient'), ('next_of_kin', 'Next of kin'), ('OTHER', 'Other'), ('N/A', 'Not applicable (if not telephone follow-up)')], default='patient', max_length=15, verbose_name='If by telephone, who did you speak to?'),
        ),
    ]
