# Generated by Django 3.2.11 on 2022-02-24 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_subject", "0012_auto_20220224_1826"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmicrobiology",
            name="sputum_requisition",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Start typing the requisition identifier or select one from this visit",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="effect_subject.subjectrequisition",
                verbose_name="Sputum requisition",
            ),
        ),
        migrations.AddField(
            model_name="microbiology",
            name="sputum_requisition",
            field=models.ForeignKey(
                blank=True,
                help_text="Start typing the requisition identifier or select one from this visit",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="effect_subject.subjectrequisition",
                verbose_name="Sputum requisition",
            ),
        ),
    ]
