# Generated by Django 3.2.11 on 2022-02-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("effect_subject", "0016_auto_20220225_0351"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicallpcsf",
            name="bios_crag",
        ),
        migrations.RemoveField(
            model_name="historicallpcsf",
            name="crag_control_result",
        ),
        migrations.RemoveField(
            model_name="historicallpcsf",
            name="crag_t1_result",
        ),
        migrations.RemoveField(
            model_name="historicallpcsf",
            name="crag_t2_result",
        ),
        migrations.RemoveField(
            model_name="lpcsf",
            name="bios_crag",
        ),
        migrations.RemoveField(
            model_name="lpcsf",
            name="crag_control_result",
        ),
        migrations.RemoveField(
            model_name="lpcsf",
            name="crag_t1_result",
        ),
        migrations.RemoveField(
            model_name="lpcsf",
            name="crag_t2_result",
        ),
        migrations.AddField(
            model_name="historicallpcsf",
            name="opening_pressure_measured",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=25,
                verbose_name="Was the opening pressure measured",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lpcsf",
            name="opening_pressure_measured",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=25,
                verbose_name="Was the opening pressure measured",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicallpcsf",
            name="reason_for_lp",
            field=models.CharField(
                choices=[
                    ("scheduled_per_protocol", "Scheduled per protocol"),
                    (
                        "clincal_deterioration",
                        "Suspected Cryptococcal meningitis / Suspected IRIS",
                    ),
                ],
                max_length=50,
                verbose_name="Reason for LP",
            ),
        ),
        migrations.AlterField(
            model_name="lpcsf",
            name="reason_for_lp",
            field=models.CharField(
                choices=[
                    ("scheduled_per_protocol", "Scheduled per protocol"),
                    (
                        "clincal_deterioration",
                        "Suspected Cryptococcal meningitis / Suspected IRIS",
                    ),
                ],
                max_length=50,
                verbose_name="Reason for LP",
            ),
        ),
    ]
