# Generated by Django 3.2.8 on 2022-03-04 11:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_lists", "0005_delete_rankinscore"),
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("effect_subject", "0024_auto_20220303_2242"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HistoricalStudyTreatment",
            new_name="HistoricalPatientTreatment",
        ),
        migrations.RenameModel(
            old_name="HistoricalStudyTreatmentDay14",
            new_name="HistoricalPatientTreatmentDay14",
        ),
        migrations.RenameModel(
            old_name="StudyTreatment",
            new_name="PatientTreatment",
        ),
        migrations.RenameModel(
            old_name="StudyTreatmentDay14",
            new_name="PatientTreatmentDay14",
        ),
        migrations.AlterModelOptions(
            name="historicalpatienttreatment",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Patient Treatment",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpatienttreatmentday14",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Patient Treatment: Day 14",
            },
        ),
        migrations.AlterModelOptions(
            name="patienttreatment",
            options={
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "get_latest_by": "modified",
                "ordering": ("-modified", "-created"),
                "verbose_name": "Patient Treatment",
                "verbose_name_plural": "Patient Treatment",
            },
        ),
        migrations.AlterModelOptions(
            name="patienttreatmentday14",
            options={
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "get_latest_by": "modified",
                "ordering": ("-modified", "-created"),
                "verbose_name": "Patient Treatment: Day 14",
                "verbose_name_plural": "Patient Treatment: Day 14",
            },
        ),
        migrations.RemoveIndex(
            model_name="patienttreatment",
            name="effect_subj_subject_4b8a9e_idx",
        ),
        migrations.RemoveIndex(
            model_name="patienttreatmentday14",
            name="effect_subj_subject_e896d0_idx",
        ),
        migrations.AddIndex(
            model_name="patienttreatment",
            index=models.Index(
                fields=["subject_visit", "site", "id"], name="effect_subj_subject_e85b2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patienttreatmentday14",
            index=models.Index(
                fields=["subject_visit", "site", "id"], name="effect_subj_subject_b2bec7_idx"
            ),
        ),
    ]
