# Generated by Django 3.2.11 on 2022-03-29 14:43

import edc_model.validators.date
import edc_protocol.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_subject", "0030_auto_20220324_1900"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmedicationadherence",
            name="pill_count_performed",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=5,
                verbose_name="Was a pill count performed",
            ),
        ),
        migrations.AddField(
            model_name="medicationadherence",
            name="pill_count_performed",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=5,
                verbose_name="Was a pill count performed",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatienthistory",
            name="neuro_abnormality_details",
            field=models.TextField(
                blank=True, null=True, verbose_name="Details of neurological abnormality?"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectvisit",
            name="last_alive_date",
            field=models.DateField(
                blank=True,
                help_text="Will be validated on the Death report",
                null=True,
                validators=[
                    edc_protocol.validators.date_not_before_study_start,
                    edc_model.validators.date.date_not_future,
                ],
                verbose_name="Date participant last known alive",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectvisit",
            name="survival_status",
            field=models.CharField(
                choices=[("alive", "Alive"), ("dead", "Deceased"), ("unknown", "Unknown")],
                default="alive",
                help_text="If YES, submit Death report",
                max_length=10,
                null=True,
                verbose_name="Participant's survival status",
            ),
        ),
        migrations.AlterField(
            model_name="patienthistory",
            name="neuro_abnormality_details",
            field=models.TextField(
                blank=True, null=True, verbose_name="Details of neurological abnormality?"
            ),
        ),
        migrations.AlterField(
            model_name="subjectvisit",
            name="last_alive_date",
            field=models.DateField(
                blank=True,
                help_text="Will be validated on the Death report",
                null=True,
                validators=[
                    edc_protocol.validators.date_not_before_study_start,
                    edc_model.validators.date.date_not_future,
                ],
                verbose_name="Date participant last known alive",
            ),
        ),
        migrations.AlterField(
            model_name="subjectvisit",
            name="survival_status",
            field=models.CharField(
                choices=[("alive", "Alive"), ("dead", "Deceased"), ("unknown", "Unknown")],
                default="alive",
                help_text="If YES, submit Death report",
                max_length=10,
                null=True,
                verbose_name="Participant's survival status",
            ),
        ),
    ]
