# Generated by Django 3.2.8 on 2022-04-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("effect_subject", "0037_auto_20220419_2126"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicallpcsf",
            name="qc_requisition",
        ),
        migrations.RemoveField(
            model_name="lpcsf",
            name="qc_requisition",
        ),
    ]
