# Generated by Django 3.2.8 on 2022-04-27 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("effect_subject", "0040_auto_20220421_2009"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsignsandsymptoms",
            name="cm_sx_patient_admitted",
        ),
        migrations.RemoveField(
            model_name="signsandsymptoms",
            name="cm_sx_patient_admitted",
        ),
    ]
