# Generated by Django 3.2.11 on 2022-05-03 16:33

import edc_model.models.fields.other_charfield
import edc_model.validators.date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_subject", "0048_auto_20220501_1555"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patienttreatmentday14",
            name="other_antibiotics_first_2w",
        ),
        migrations.RemoveField(
            model_name="patienttreatmentday14",
            name="other_drugs_first_2w",
        ),
        migrations.RemoveField(
            model_name="patienttreatmentday14",
            name="site",
        ),
        migrations.RemoveField(
            model_name="patienttreatmentday14",
            name="subject_visit",
        ),
        migrations.RenameField(
            model_name="historicalpatienttreatment",
            old_name="steroids_course_duration",
            new_name="steroids_course",
        ),
        migrations.RenameField(
            model_name="historicalpatienttreatment",
            old_name="which_steroids_other",
            new_name="steroids_given_other",
        ),
        migrations.RenameField(
            model_name="patienttreatment",
            old_name="steroids_course_duration",
            new_name="steroids_course",
        ),
        migrations.RenameField(
            model_name="patienttreatment",
            old_name="which_steroids_other",
            new_name="steroids_given_other",
        ),
        migrations.RenameField(
            model_name="historicalpatienttreatment",
            old_name="antibiotics_other",
            new_name="antibiotics_given_other",
        ),
        migrations.RenameField(
            model_name="historicalpatienttreatment",
            old_name="cm_tx_administered",
            new_name="cm_tx",
        ),
        migrations.RenameField(
            model_name="historicalpatienttreatment",
            old_name="steroids_administered",
            new_name="steroids",
        ),
        migrations.RenameField(
            model_name="historicalpatienttreatment",
            old_name="which_steroids",
            new_name="steroids_given",
        ),
        migrations.RenameField(
            model_name="patienttreatment",
            old_name="antibiotics_other",
            new_name="antibiotics_given_other",
        ),
        migrations.RenameField(
            model_name="patienttreatment",
            old_name="cm_tx_administered",
            new_name="cm_tx",
        ),
        migrations.RenameField(
            model_name="patienttreatment",
            old_name="steroids_administered",
            new_name="steroids",
        ),
        migrations.RenameField(
            model_name="patienttreatment",
            old_name="which_steroids",
            new_name="steroids_given",
        ),
        migrations.AddField(
            model_name="historicalpatienttreatment",
            name="antibiotics",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="-",
                max_length=15,
                verbose_name="Has the patient been prescribed antibiotics?",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalpatienttreatment",
            name="antibiotics_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[edc_model.validators.date.date_not_future],
                verbose_name="If YES, give date",
            ),
        ),
        migrations.AddField(
            model_name="historicalpatienttreatment",
            name="co_trimoxazole_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[edc_model.validators.date.date_not_future],
                verbose_name="If YES, give date",
            ),
        ),
        migrations.AddField(
            model_name="historicalpatienttreatment",
            name="co_trimoxazole_reason_no",
            field=models.CharField(
                choices=[
                    ("deferred_local_clinic", "Deferred to local clinic"),
                    ("contraindicated", "Contraindicated"),
                    ("OTHER", "Other, please specify below ..."),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                max_length=30,
                verbose_name="If NO, give reason",
            ),
        ),
        migrations.AddField(
            model_name="historicalpatienttreatment",
            name="co_trimoxazole_reason_no_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If other, please specify ...",
            ),
        ),
        migrations.AddField(
            model_name="historicalpatienttreatment",
            name="other_drugs",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="-",
                max_length=15,
                verbose_name="Has the patient been prescribed any other drugs/interventions?",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalpatienttreatment",
            name="other_drugs_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[edc_model.validators.date.date_not_future],
                verbose_name="If YES, give date",
            ),
        ),
        migrations.AddField(
            model_name="historicalpatienttreatment",
            name="other_drugs_given_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If other, please specify ...",
            ),
        ),
        migrations.AddField(
            model_name="historicalpatienttreatment",
            name="steroids_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[edc_model.validators.date.date_not_future],
                verbose_name="If YES, give date",
            ),
        ),
        migrations.AddField(
            model_name="historicalpatienttreatment",
            name="tb_tx",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="-",
                max_length=15,
                verbose_name="Has the patient been put on TB preventive therapy?",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalpatienttreatment",
            name="tb_tx_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[edc_model.validators.date.date_not_future],
                verbose_name="If YES, give date",
            ),
        ),
        migrations.AddField(
            model_name="historicalpatienttreatment",
            name="tb_tx_reason_no",
            field=models.CharField(
                choices=[
                    ("deferred_local_clinic", "Deferred to local clinic"),
                    ("contraindicated", "Contraindicated"),
                    ("OTHER", "Other, please specify below ..."),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                max_length=30,
                verbose_name="If NO, give reason",
            ),
        ),
        migrations.AddField(
            model_name="historicalpatienttreatment",
            name="tb_tx_reason_no_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If other, please specify ...",
            ),
        ),
        migrations.AddField(
            model_name="patienttreatment",
            name="antibiotics_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[edc_model.validators.date.date_not_future],
                verbose_name="If YES, give date",
            ),
        ),
        migrations.AddField(
            model_name="patienttreatment",
            name="antibiotics_given",
            field=models.ManyToManyField(
                blank=True,
                to="effect_lists.Antibiotics",
                verbose_name="If YES, which antibiotics?",
            ),
        ),
        migrations.AddField(
            model_name="patienttreatment",
            name="co_trimoxazole_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[edc_model.validators.date.date_not_future],
                verbose_name="If YES, give date",
            ),
        ),
        migrations.AddField(
            model_name="patienttreatment",
            name="co_trimoxazole_reason_no",
            field=models.CharField(
                choices=[
                    ("deferred_local_clinic", "Deferred to local clinic"),
                    ("contraindicated", "Contraindicated"),
                    ("OTHER", "Other, please specify below ..."),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                max_length=30,
                verbose_name="If NO, give reason",
            ),
        ),
        migrations.AddField(
            model_name="patienttreatment",
            name="co_trimoxazole_reason_no_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If other, please specify ...",
            ),
        ),
        migrations.AddField(
            model_name="patienttreatment",
            name="other_drugs",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="-",
                max_length=15,
                verbose_name="Has the patient been prescribed any other drugs/interventions?",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patienttreatment",
            name="other_drugs_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[edc_model.validators.date.date_not_future],
                verbose_name="If YES, give date",
            ),
        ),
        migrations.AddField(
            model_name="patienttreatment",
            name="other_drugs_given",
            field=models.ManyToManyField(
                blank=True,
                to="effect_lists.Drugs",
                verbose_name="If YES, which drugs/interventions?",
            ),
        ),
        migrations.AddField(
            model_name="patienttreatment",
            name="other_drugs_given_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If other, please specify ...",
            ),
        ),
        migrations.AddField(
            model_name="patienttreatment",
            name="steroids_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[edc_model.validators.date.date_not_future],
                verbose_name="If YES, give date",
            ),
        ),
        migrations.AddField(
            model_name="patienttreatment",
            name="tb_tx",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="-",
                max_length=15,
                verbose_name="Has the patient been put on TB preventive therapy?",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patienttreatment",
            name="tb_tx_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[edc_model.validators.date.date_not_future],
                verbose_name="If YES, give date",
            ),
        ),
        migrations.AddField(
            model_name="patienttreatment",
            name="tb_tx_reason_no",
            field=models.CharField(
                choices=[
                    ("deferred_local_clinic", "Deferred to local clinic"),
                    ("contraindicated", "Contraindicated"),
                    ("OTHER", "Other, please specify below ..."),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                max_length=30,
                verbose_name="If NO, give reason",
            ),
        ),
        migrations.AddField(
            model_name="patienttreatment",
            name="tb_tx_reason_no_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If other, please specify ...",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatienttreatment",
            name="cm_confirmed",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Cryptococcal meningitis confirmed?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatienttreatment",
            name="cm_tx_given",
            field=models.CharField(
                choices=[
                    ("1w_amb_5fc", "1 week AmB + 5FC"),
                    ("OTHER", "Other, please specify below ..."),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                max_length=15,
                verbose_name="If YES, treatment given?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatienttreatment",
            name="cm_tx_given_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If other, please specify ...",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatienttreatment",
            name="co_trimoxazole",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Has the patient been prescribed co-trimoxazole?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatienttreatment",
            name="tb_tx_given_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If other, please specify ...",
            ),
        ),
        migrations.RemoveField(
            model_name="patienttreatment",
            name="antibiotics",
        ),
        migrations.AddField(
            model_name="patienttreatment",
            name="antibiotics",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="-",
                max_length=15,
                verbose_name="Has the patient been prescribed antibiotics?",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="patienttreatment",
            name="cm_confirmed",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Cryptococcal meningitis confirmed?",
            ),
        ),
        migrations.AlterField(
            model_name="patienttreatment",
            name="cm_tx_given",
            field=models.CharField(
                choices=[
                    ("1w_amb_5fc", "1 week AmB + 5FC"),
                    ("OTHER", "Other, please specify below ..."),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                max_length=15,
                verbose_name="If YES, treatment given?",
            ),
        ),
        migrations.AlterField(
            model_name="patienttreatment",
            name="cm_tx_given_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If other, please specify ...",
            ),
        ),
        migrations.AlterField(
            model_name="patienttreatment",
            name="co_trimoxazole",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Has the patient been prescribed co-trimoxazole?",
            ),
        ),
        migrations.AlterField(
            model_name="patienttreatment",
            name="tb_tx_given",
            field=models.ManyToManyField(
                blank=True,
                to="effect_lists.TbTreatments",
                verbose_name="If YES, which treatment?",
            ),
        ),
        migrations.AlterField(
            model_name="patienttreatment",
            name="tb_tx_given_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If other, please specify ...",
            ),
        ),
        migrations.DeleteModel(
            name="HistoricalPatientTreatmentDay14",
        ),
        migrations.DeleteModel(
            name="PatientTreatmentDay14",
        ),
    ]
