# Generated by Django 3.2.8 on 2022-05-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_subject", "0059_auto_20220510_1544"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnoses",
            name="patient_admitted",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                help_text="If YES, complete Hospitalization and AE Initial reports.",
                max_length=15,
                verbose_name="Has the patient been admitted due to any of these diagnoses?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldiagnoses",
            name="patient_admitted",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                help_text="If YES, complete Hospitalization and AE Initial reports.",
                max_length=15,
                verbose_name="Has the patient been admitted due to any of these diagnoses?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmentalstatus",
            name="patient_admitted",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                help_text="If YES, complete Hospitalization and AE Initial reports.",
                max_length=15,
                verbose_name="Has the patient been admitted due to these symptoms?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsignsandsymptoms",
            name="patient_admitted",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                help_text="If YES, complete Hospitalization and AE Initial reports.",
                max_length=15,
                verbose_name="Has the patient been admitted due to any of these signs or symptoms?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectvisit",
            name="hospitalized",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("unknown", "Unknown"),
                    ("N/A", "Not applicable (if missed)"),
                ],
                default="N/A",
                help_text="If YES, complete Hospitalization and AE Initial reports.",
                max_length=15,
                verbose_name="Has the patient been hospitalized since the last assessment?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalvitalsigns",
            name="patient_admitted",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                help_text="If YES, complete Hospitalization and AE Initial reports.",
                max_length=15,
                verbose_name="Has the patient been admitted due to any of the above?",
            ),
        ),
        migrations.AlterField(
            model_name="mentalstatus",
            name="patient_admitted",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                help_text="If YES, complete Hospitalization and AE Initial reports.",
                max_length=15,
                verbose_name="Has the patient been admitted due to these symptoms?",
            ),
        ),
        migrations.AlterField(
            model_name="signsandsymptoms",
            name="patient_admitted",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                help_text="If YES, complete Hospitalization and AE Initial reports.",
                max_length=15,
                verbose_name="Has the patient been admitted due to any of these signs or symptoms?",
            ),
        ),
        migrations.AlterField(
            model_name="subjectvisit",
            name="hospitalized",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("unknown", "Unknown"),
                    ("N/A", "Not applicable (if missed)"),
                ],
                default="N/A",
                help_text="If YES, complete Hospitalization and AE Initial reports.",
                max_length=15,
                verbose_name="Has the patient been hospitalized since the last assessment?",
            ),
        ),
        migrations.AlterField(
            model_name="vitalsigns",
            name="patient_admitted",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                help_text="If YES, complete Hospitalization and AE Initial reports.",
                max_length=15,
                verbose_name="Has the patient been admitted due to any of the above?",
            ),
        ),
    ]
