# Generated by Django 3.2.13 on 2022-06-15 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("effect_subject", "0072_auto_20220615_1249"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalhistory",
            name="site",
        ),
        migrations.RemoveField(
            model_name="medicalhistory",
            name="subject_visit",
        ),
        migrations.DeleteModel(
            name="HistoricalMedicalHistory",
        ),
        migrations.DeleteModel(
            name="MedicalHistory",
        ),
    ]
