# Generated by Django 3.2.13 on 2022-06-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("effect_subject", "0076_auto_20220623_1633"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chestxray",
            name="chest_xray_results_other",
            field=models.TextField(
                blank=True, null=True, verbose_name="If other, please specify ..."
            ),
        ),
        migrations.AlterField(
            model_name="historicalchestxray",
            name="chest_xray_results_other",
            field=models.TextField(
                blank=True, null=True, verbose_name="If other, please specify ..."
            ),
        ),
    ]
