# Generated by Django 3.2.13 on 2022-07-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_subject", "0081_auto_20220711_1230"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodresultschem",
            name="missing",
            field=models.TextField(
                editable=False,
                help_text="calculated string of field names that have been left blank",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bloodresultschem",
            name="missing_count",
            field=models.IntegerField(
                default=0, editable=False, help_text="A count of fields left blank"
            ),
        ),
        migrations.AddField(
            model_name="bloodresultsfbc",
            name="missing",
            field=models.TextField(
                editable=False,
                help_text="calculated string of field names that have been left blank",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bloodresultsfbc",
            name="missing_count",
            field=models.IntegerField(
                default=0, editable=False, help_text="A count of fields left blank"
            ),
        ),
        migrations.AddField(
            model_name="historicalbloodresultschem",
            name="missing",
            field=models.TextField(
                editable=False,
                help_text="calculated string of field names that have been left blank",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalbloodresultschem",
            name="missing_count",
            field=models.IntegerField(
                default=0, editable=False, help_text="A count of fields left blank"
            ),
        ),
        migrations.AddField(
            model_name="historicalbloodresultsfbc",
            name="missing",
            field=models.TextField(
                editable=False,
                help_text="calculated string of field names that have been left blank",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalbloodresultsfbc",
            name="missing_count",
            field=models.IntegerField(
                default=0, editable=False, help_text="A count of fields left blank"
            ),
        ),
        migrations.AddField(
            model_name="historicalurinalysis",
            name="missing",
            field=models.TextField(
                editable=False,
                help_text="calculated string of field names that have been left blank",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalurinalysis",
            name="missing_count",
            field=models.IntegerField(
                default=0, editable=False, help_text="A count of fields left blank"
            ),
        ),
        migrations.AddField(
            model_name="urinalysis",
            name="missing",
            field=models.TextField(
                editable=False,
                help_text="calculated string of field names that have been left blank",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="urinalysis",
            name="missing_count",
            field=models.IntegerField(
                default=0, editable=False, help_text="A count of fields left blank"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmedicationadherence",
            name="pill_count_not_performed_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="If not performed, please explain ..."
            ),
        ),
        migrations.AlterField(
            model_name="medicationadherence",
            name="pill_count_not_performed_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="If not performed, please explain ..."
            ),
        ),
    ]
