# Generated by Django 3.2 on 2022-09-29 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("effect_lists", "0013_auto_20220927_1831"),
        ("sites", "0002_alter_domain_unique"),
        ("effect_subject", "0093_auto_20220929_1222"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HistoricalPatientTreatment",
            new_name="HistoricalParticipantTreatment",
        ),
        migrations.RenameModel(
            old_name="PatientTreatment",
            new_name="ParticipantTreatment",
        ),
        migrations.AlterModelOptions(
            name="historicalparticipanttreatment",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Participant Treatment",
                "verbose_name_plural": "historical Participant Treatment",
            },
        ),
        migrations.AlterModelOptions(
            name="participanttreatment",
            options={
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "get_latest_by": "modified",
                "ordering": ("-modified", "-created"),
                "verbose_name": "Participant Treatment",
                "verbose_name_plural": "Participant Treatment",
            },
        ),
        migrations.RemoveIndex(
            model_name="participanttreatment",
            name="effect_subj_subject_e85b2f_idx",
        ),
        migrations.RemoveIndex(
            model_name="participanttreatment",
            name="effect_subj_subject_4748cd_idx",
        ),
        migrations.AddIndex(
            model_name="participanttreatment",
            index=models.Index(
                fields=["subject_visit", "site", "id"], name="effect_subj_subject_ed4677_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="participanttreatment",
            index=models.Index(
                fields=["subject_visit", "report_datetime"],
                name="effect_subj_subject_86f5cb_idx",
            ),
        ),
    ]
