# Generated by Django 3.2.16 on 2022-10-06 09:21

from django.db import migrations, models
import edc_model.validators.date


class Migration(migrations.Migration):

    dependencies = [
        ("effect_subject", "0095_auto_20220930_1306"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodresultschem",
            name="assay_datetime",
            field=models.DateTimeField(
                blank=True,
                null=True,
                validators=[edc_model.validators.date.datetime_not_future],
                verbose_name="Result assay date and time",
            ),
        ),
        migrations.AlterField(
            model_name="bloodresultsfbc",
            name="assay_datetime",
            field=models.DateTimeField(
                blank=True,
                null=True,
                validators=[edc_model.validators.date.datetime_not_future],
                verbose_name="Result assay date and time",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbloodresultschem",
            name="assay_datetime",
            field=models.DateTimeField(
                blank=True,
                null=True,
                validators=[edc_model.validators.date.datetime_not_future],
                verbose_name="Result assay date and time",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbloodresultsfbc",
            name="assay_datetime",
            field=models.DateTimeField(
                blank=True,
                null=True,
                validators=[edc_model.validators.date.datetime_not_future],
                verbose_name="Result assay date and time",
            ),
        ),
        migrations.AlterField(
            model_name="historicalurinalysis",
            name="assay_datetime",
            field=models.DateTimeField(
                blank=True,
                null=True,
                validators=[edc_model.validators.date.datetime_not_future],
                verbose_name="Result assay date and time",
            ),
        ),
        migrations.AlterField(
            model_name="urinalysis",
            name="assay_datetime",
            field=models.DateTimeField(
                blank=True,
                null=True,
                validators=[edc_model.validators.date.datetime_not_future],
                verbose_name="Result assay date and time",
            ),
        ),
    ]
