# Generated by Django 4.1.7 on 2023-06-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("effect_subject", "0102_alter_bloodresultschem_ast_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalparticipanthistory",
            name="admission_indication",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="If YES, what is the indication for admission?",
            ),
        ),
        migrations.AddField(
            model_name="historicalparticipanthistory",
            name="inpatient",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                help_text="(answer NO if admission purely for screening LP)",
                max_length=5,
                null=True,
                verbose_name="Is the participant currently an inpatient?",
            ),
        ),
        migrations.AddField(
            model_name="participanthistory",
            name="admission_indication",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="If YES, what is the indication for admission?",
            ),
        ),
        migrations.AddField(
            model_name="participanthistory",
            name="inpatient",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                help_text="(answer NO if admission purely for screening LP)",
                max_length=5,
                null=True,
                verbose_name="Is the participant currently an inpatient?",
            ),
        ),
    ]
