# Generated by Django 4.1.7 on 2023-08-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("effect_subject", "0105_alter_arvhistory_on_art_at_crag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmentalstatus",
            name="modified_rankin_score",
            field=models.CharField(
                choices=[
                    ("0", "[0] No symptoms"),
                    (
                        "1",
                        "[1] No significant disability. Able to carry out usual activities, despite some symptoms.",
                    ),
                    (
                        "2",
                        "[2] Slight disability. Able to look after own affairs without assistance, but unable to carry out all previous activities.",
                    ),
                    (
                        "3",
                        "[3] Moderate disability. Requires some help, but able to walk unassisted.",
                    ),
                    (
                        "4",
                        "[4] Moderately severe disability. Unable to attend to own bodily needs without assistance, and unable to walk unassisted.",
                    ),
                    (
                        "5",
                        "[5] Severe disability. Requires constant nursing care and attention, bedridden, incontinent.",
                    ),
                    ("6", "[6] Dead"),
                ],
                max_length=15,
                verbose_name="Modified Rankin Score",
            ),
        ),
        migrations.AlterField(
            model_name="mentalstatus",
            name="modified_rankin_score",
            field=models.CharField(
                choices=[
                    ("0", "[0] No symptoms"),
                    (
                        "1",
                        "[1] No significant disability. Able to carry out usual activities, despite some symptoms.",
                    ),
                    (
                        "2",
                        "[2] Slight disability. Able to look after own affairs without assistance, but unable to carry out all previous activities.",
                    ),
                    (
                        "3",
                        "[3] Moderate disability. Requires some help, but able to walk unassisted.",
                    ),
                    (
                        "4",
                        "[4] Moderately severe disability. Unable to attend to own bodily needs without assistance, and unable to walk unassisted.",
                    ),
                    (
                        "5",
                        "[5] Severe disability. Requires constant nursing care and attention, bedridden, incontinent.",
                    ),
                    ("6", "[6] Dead"),
                ],
                max_length=15,
                verbose_name="Modified Rankin Score",
            ),
        ),
    ]
