# Generated by Django 5.1.1 on 2024-09-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("effect_subject", "0115_alter_healtheconomicsevent_hospital_time_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bloodculture",
            options={
                "default_manager_name": "objects",
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "verbose_name": "Blood Culture",
                "verbose_name_plural": "Blood Culture",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalbloodculture",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Blood Culture",
                "verbose_name_plural": "historical Blood Culture",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalstudymedication",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Study Medication",
                "verbose_name_plural": "historical Study Medication",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalstudymedicationbaseline",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Study Medication (Baseline)",
                "verbose_name_plural": "historical Study Medication (Baseline)",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalstudymedicationfollowup",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Study Medication",
                "verbose_name_plural": "historical Study Medication",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsubjectrequisition",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Subject Requisition",
                "verbose_name_plural": "historical Subject Requisitions",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsubjectvisit",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Subject Visit",
                "verbose_name_plural": "historical Subject Visits",
            },
        ),
        migrations.AlterModelOptions(
            name="studymedication",
            options={
                "default_manager_name": "objects",
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "verbose_name": "Study Medication",
                "verbose_name_plural": "Study Medication",
            },
        ),
        migrations.AlterModelOptions(
            name="studymedicationbaseline",
            options={
                "verbose_name": "Study Medication (Baseline)",
                "verbose_name_plural": "Study Medication (Baseline)",
            },
        ),
        migrations.AlterModelOptions(
            name="studymedicationfollowup",
            options={
                "verbose_name": "Study Medication",
                "verbose_name_plural": "Study Medication",
            },
        ),
        migrations.AlterModelOptions(
            name="subjectrequisition",
            options={
                "default_manager_name": "objects",
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "verbose_name": "Subject Requisition",
                "verbose_name_plural": "Subject Requisitions",
            },
        ),
        migrations.AlterModelOptions(
            name="subjectvisit",
            options={
                "default_manager_name": "objects",
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "verbose_name": "Subject Visit",
                "verbose_name_plural": "Subject Visits",
            },
        ),
    ]
