# Generated by Django 5.1.3 on 2025-01-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_subject", "0120_arvhistory_viral_load_result_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="arvhistory",
            name="viral_load_quantifier",
            field=models.CharField(
                choices=[("=", "="), (">", ">"), ("<", "<"), ("N/A", "Not applicable")],
                help_text="If lower than detection limit (LDL), use '<' and enter the lab detection limit value above.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalarvhistory",
            name="viral_load_quantifier",
            field=models.CharField(
                choices=[("=", "="), (">", ">"), ("<", "<"), ("N/A", "Not applicable")],
                help_text="If lower than detection limit (LDL), use '<' and enter the lab detection limit value above.",
                max_length=10,
                null=True,
            ),
        ),
    ]
