# Generated by Django 5.1.3 on 2025-01-03 12:46
from django.db import migrations
from edc_constants.constants import NO, NOT_APPLICABLE
from edc_utils import get_utcnow, truncate_string
from tqdm import tqdm


def set_vl_quantifier_na_if_na(apps, schema_editor):
    model_cls = apps.get_model("effect_subject.arvhistory")

    qs = model_cls.objects.filter(
        has_viral_load_result=NO,
        viral_load_result=None,
        retired_viral_load_result=None,
        viral_load_date=None,
        viral_load_date_estimated=NOT_APPLICABLE,
    )
    total = qs.count()
    print(
        f"\nSetting `viral_load_quantifier` to `N/A` for {total} Arv History "
        "instances without vl result ..."
    )
    user_modified = truncate_string(string=__name__, max_length=50)
    for obj in tqdm(qs, total=total):
        obj.viral_load_quantifier = NOT_APPLICABLE
        obj.modified = get_utcnow()
        obj.user_modified = user_modified
        obj.save()
        print(f"Set `viral_load_quantifier` for {obj} to `N/A`")
    print("Done migrating")


class Migration(migrations.Migration):

    dependencies = [
        ("effect_subject", "0121_arvhistory_viral_load_quantifier_and_more"),
    ]

    operations = [migrations.RunPython(set_vl_quantifier_na_if_na)]
