# Generated by Django 5.2.3 on 2025-06-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_subject", "0124_alter_bloodresultschem_tbil_units_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodresultschem",
            name="abnormal_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bloodresultschem",
            name="errors",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bloodresultschem",
            name="reportable_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bloodresultsfbc",
            name="abnormal_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bloodresultsfbc",
            name="errors",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bloodresultsfbc",
            name="reportable_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalbloodresultschem",
            name="abnormal_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalbloodresultschem",
            name="errors",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalbloodresultschem",
            name="reportable_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalbloodresultsfbc",
            name="abnormal_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalbloodresultsfbc",
            name="errors",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalbloodresultsfbc",
            name="reportable_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalurinalysis",
            name="abnormal_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalurinalysis",
            name="errors",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalurinalysis",
            name="reportable_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="urinalysis",
            name="abnormal_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="urinalysis",
            name="errors",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="urinalysis",
            name="reportable_summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
