# Generated by Django 3.2 on 2022-09-30 11:06

import django.contrib.sites.managers
from django.db import migrations
import edc_identifier.managers


class Migration(migrations.Migration):
    dependencies = [
        ("effect_consent", "0005_auto_20220910_2045"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="subjectconsent",
            managers=[
                ("on_site", django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="subjectreconsent",
            managers=[
                ("on_site", django.contrib.sites.managers.CurrentSiteManager()),
                ("objects", edc_identifier.managers.SubjectIdentifierManager()),
            ],
        ),
    ]
