# Generated by Django 4.2.10 on 2024-02-29 05:29

import _socket
from django.db import migrations, models
import django.db.models.deletion
import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
import django_audit_fields.fields.uuid_auto_field
import django_audit_fields.models.audit_model_mixin
import django_revision.revision_field
import edc_action_item.managers
import edc_sites.managers
import edc_utils.date
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("edc_action_item", "0037_remove_actionitem_reference_model_and_more"),
        ("sites", "0002_alter_domain_unique"),
        ("effect_consent", "0016_historicalsubjectconsentv2_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SubjectConsentUpdateV2",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="assessment_score",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="citizen",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="completed_by_next_of_kin",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="confirm_identity",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="consent_copy",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="consent_definition_name",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="consent_identifier",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="consent_reviewed",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="consent_signature",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="dm_comment",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="dob",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="guardian_name",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="identity",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="identity_type",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="initials",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="is_able",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="is_dob_estimated",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="is_incarcerated",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="is_literate",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="is_verified_datetime",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="language",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="legal_marriage",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="marriage_certificate",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="marriage_certificate_no",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="may_store_genetic_samples",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="may_store_samples",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="model_name",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="report_datetime",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="screening_datetime",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="screening_identifier",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="sid",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="study_questions",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="subject_identifier_aka",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="subject_identifier_as_pk",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="subject_type",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="update_versions",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="verified_by",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="version",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsentupdatev2",
            name="witness_name",
        ),
        migrations.AddField(
            model_name="historicalsubjectconsentupdatev2",
            name="action_identifier",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="historicalsubjectconsentupdatev2",
            name="action_item",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_action_item.actionitem",
            ),
        ),
        migrations.AddField(
            model_name="historicalsubjectconsentupdatev2",
            name="action_item_reason",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="historicalsubjectconsentupdatev2",
            name="parent_action_identifier",
            field=models.CharField(
                blank=True,
                help_text="action identifier that links to parent reference model instance.",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalsubjectconsentupdatev2",
            name="parent_action_item",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_action_item.actionitem",
            ),
        ),
        migrations.AddField(
            model_name="historicalsubjectconsentupdatev2",
            name="related_action_identifier",
            field=models.CharField(
                blank=True,
                help_text="action identifier that links to related reference model instance.",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalsubjectconsentupdatev2",
            name="related_action_item",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_action_item.actionitem",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectconsent",
            name="hcw_data_sharing",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Does the ppt agree to sharing study information with their primary healthcare provider? ",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectconsent",
            name="he_substudy",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Does the ppt agree to participate in the Health Economics sub-study?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectconsent",
            name="sample_export",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Does the ppt agree to export of stored samples internationally?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectconsent",
            name="sample_storage",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Does the ppt agree to storage of samples in-country?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectconsentupdatev2",
            name="consent_datetime",
            field=models.DateTimeField(
                default=edc_utils.date.get_utcnow, verbose_name="Consent date and time"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectconsentupdatev2",
            name="hcw_data_sharing",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Does the ppt agree to sharing study information with their primary healthcare provider? ",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectconsentupdatev2",
            name="he_substudy",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Does the ppt agree to participate in the Health Economics sub-study?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectconsentupdatev2",
            name="sample_export",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Does the ppt agree to export of stored samples internationally?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectconsentupdatev2",
            name="sample_storage",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Does the ppt agree to storage of samples in-country?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectconsentupdatev2",
            name="subject_identifier",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="historicalsubjectconsentv1",
            name="hcw_data_sharing",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Does the ppt agree to sharing study information with their primary healthcare provider? ",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectconsentv1",
            name="he_substudy",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Does the ppt agree to participate in the Health Economics sub-study?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectconsentv1",
            name="sample_export",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Does the ppt agree to export of stored samples internationally?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectconsentv1",
            name="sample_storage",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Does the ppt agree to storage of samples in-country?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectconsentv2",
            name="hcw_data_sharing",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Does the ppt agree to sharing study information with their primary healthcare provider? ",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectconsentv2",
            name="he_substudy",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Does the ppt agree to participate in the Health Economics sub-study?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectconsentv2",
            name="sample_export",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Does the ppt agree to export of stored samples internationally?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectconsentv2",
            name="sample_storage",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Does the ppt agree to storage of samples in-country?",
            ),
        ),
        migrations.AlterField(
            model_name="subjectconsent",
            name="hcw_data_sharing",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Does the ppt agree to sharing study information with their primary healthcare provider? ",
            ),
        ),
        migrations.AlterField(
            model_name="subjectconsent",
            name="he_substudy",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Does the ppt agree to participate in the Health Economics sub-study?",
            ),
        ),
        migrations.AlterField(
            model_name="subjectconsent",
            name="sample_export",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Does the ppt agree to export of stored samples internationally?",
            ),
        ),
        migrations.AlterField(
            model_name="subjectconsent",
            name="sample_storage",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Does the ppt agree to storage of samples in-country?",
            ),
        ),
        migrations.CreateModel(
            name="SubjectConsentUpdateV2",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        editable=False,
                        help_text="System field. Git repository tag:branch:commit.",
                        max_length=75,
                        null=True,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(blank=True, max_length=10, verbose_name="Device created"),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Device modified"
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject_identifier", models.CharField(max_length=50, unique=True)),
                (
                    "action_identifier",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "parent_action_identifier",
                    models.CharField(
                        blank=True,
                        help_text="action identifier that links to parent reference model instance.",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "related_action_identifier",
                    models.CharField(
                        blank=True,
                        help_text="action identifier that links to related reference model instance.",
                        max_length=30,
                        null=True,
                    ),
                ),
                ("action_item_reason", models.TextField(editable=False, null=True)),
                (
                    "he_substudy",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        max_length=15,
                        verbose_name="Does the ppt agree to participate in the Health Economics sub-study?",
                    ),
                ),
                (
                    "sample_storage",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        max_length=15,
                        verbose_name="Does the ppt agree to storage of samples in-country?",
                    ),
                ),
                (
                    "sample_export",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        max_length=15,
                        verbose_name="Does the ppt agree to export of stored samples internationally?",
                    ),
                ),
                (
                    "hcw_data_sharing",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        max_length=15,
                        verbose_name="Does the ppt agree to sharing study information with their primary healthcare provider? ",
                    ),
                ),
                (
                    "consent_datetime",
                    models.DateTimeField(
                        default=edc_utils.date.get_utcnow, verbose_name="Consent date and time"
                    ),
                ),
                (
                    "action_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="edc_action_item.actionitem",
                    ),
                ),
                (
                    "parent_action_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="edc_action_item.actionitem",
                    ),
                ),
                (
                    "related_action_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="edc_action_item.actionitem",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consent Version 2 (Update)",
                "verbose_name_plural": "Consent Version 2 (Update)",
                "abstract": False,
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=[
                            "action_identifier",
                            "action_item",
                            "related_action_item",
                            "parent_action_item",
                        ],
                        name="effect_cons_action__9c0518_idx",
                    )
                ],
            },
            managers=[
                ("on_site", edc_sites.managers.CurrentSiteManager()),
                ("objects", edc_action_item.managers.ActionIdentifierModelManager()),
            ],
        ),
    ]
