# Generated by Django 5.2.4 on 2025-09-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_consent", "0025_alter_historicalsubjectconsent_revision_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsubjectconsent",
            name="ethnicity",
            field=models.CharField(
                editable=False, help_text="from screening", max_length=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalsubjectconsentv1",
            name="ethnicity",
            field=models.CharField(
                editable=False, help_text="from screening", max_length=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalsubjectconsentv2",
            name="ethnicity",
            field=models.CharField(
                editable=False, help_text="from screening", max_length=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="subjectconsent",
            name="ethnicity",
            field=models.CharField(
                editable=False, help_text="from screening", max_length=15, null=True
            ),
        ),
    ]
