# Generated by Django 5.2.7 on 2025-10-08 07:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_consent", "0029_alter_historicalsubjectconsent_revision_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubjectconsentupdatev2",
            name="consent_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Consent date and time"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectreconsent",
            name="report_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="subjectconsentupdatev2",
            name="consent_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Consent date and time"
            ),
        ),
        migrations.AlterField(
            model_name="subjectreconsent",
            name="report_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
