# Generated by Django 6.0.1 on 2026-01-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "effect_consent",
            "0030_alter_historicalsubjectconsentupdatev2_consent_datetime_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubjectconsent",
            name="consent_definition_name",
            field=models.CharField(
                default="",
                editable=False,
                max_length=50,
                verbose_name="Consent definition",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectconsentv1",
            name="consent_definition_name",
            field=models.CharField(
                default="",
                editable=False,
                max_length=50,
                verbose_name="Consent definition",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectconsentv2",
            name="consent_definition_name",
            field=models.CharField(
                default="",
                editable=False,
                max_length=50,
                verbose_name="Consent definition",
            ),
        ),
        migrations.AlterField(
            model_name="subjectconsent",
            name="consent_definition_name",
            field=models.CharField(
                default="",
                editable=False,
                max_length=50,
                verbose_name="Consent definition",
            ),
        ),
    ]
