# Generated by Django 5.1.3 on 2025-01-16 10:15

import edc_sites.managers
import edc_visit_schedule.model_mixins.on_schedule_model_mixin
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("effect_prn", "0016_alter_endofstudy_site_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="onschedule",
            managers=[
                ("on_site", edc_sites.managers.CurrentSiteManager()),
                (
                    "objects",
                    edc_visit_schedule.model_mixins.on_schedule_model_mixin.OnScheduleManager(),
                ),
            ],
        ),
    ]
