# Generated by Django 5.2.6 on 2025-09-22 12:31

import edc_utils.date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_prn", "0020_alter_historicalonschedule_onschedule_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallosstofollowup",
            name="report_datetime",
            field=models.DateTimeField(
                default=edc_utils.date.get_utcnow, verbose_name="Report Date and Time"
            ),
        ),
        migrations.AlterField(
            model_name="losstofollowup",
            name="report_datetime",
            field=models.DateTimeField(
                default=edc_utils.date.get_utcnow, verbose_name="Report Date and Time"
            ),
        ),
    ]
