# Generated by Django 5.2.10 on 2026-04-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "effect_prn",
            "0024_historicalprotocoldeviationviolation_action_required_followup_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalprotocoldeviationviolation",
            name="action_required_followup",
            field=models.CharField(
                choices=[
                    (
                        "MISSED_GT_2D_INDUCTION_RX",
                        "Missed >2 days INDUCTION Rx (>2 doses FLU and/or >8 doses 5FC)",
                    ),
                    (
                        "MISSED_GT_14D_CONSOLIDATION_RX",
                        "Missed >14 days CONSOLIDATION Rx (800mg fluconazole)",
                    ),
                    (
                        "MISSED_GT_14D_MAINTENANCE_RX",
                        "Missed >14 days MAINTENANCE Rx (200mg fluconazole)",
                    ),
                    ("ENROLLED_IN_ERROR", "Ppt enrolled in error"),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                help_text="Only applicable if the patient remains on study but data analysis will be modified",
                max_length=50,
                verbose_name="Which conditions apply?",
            ),
        ),
        migrations.AlterField(
            model_name="protocoldeviationviolation",
            name="action_required_followup",
            field=models.CharField(
                choices=[
                    (
                        "MISSED_GT_2D_INDUCTION_RX",
                        "Missed >2 days INDUCTION Rx (>2 doses FLU and/or >8 doses 5FC)",
                    ),
                    (
                        "MISSED_GT_14D_CONSOLIDATION_RX",
                        "Missed >14 days CONSOLIDATION Rx (800mg fluconazole)",
                    ),
                    (
                        "MISSED_GT_14D_MAINTENANCE_RX",
                        "Missed >14 days MAINTENANCE Rx (200mg fluconazole)",
                    ),
                    ("ENROLLED_IN_ERROR", "Ppt enrolled in error"),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                help_text="Only applicable if the patient remains on study but data analysis will be modified",
                max_length=50,
                verbose_name="Which conditions apply?",
            ),
        ),
    ]
