# Generated by Django 5.2.10 on 2026-04-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "effect_prn",
            "0025_alter_historicalprotocoldeviationviolation_action_required_followup_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalprotocoldeviationviolation",
            name="action_required_followup",
        ),
        migrations.RemoveField(
            model_name="protocoldeviationviolation",
            name="action_required_followup",
        ),
        migrations.AddField(
            model_name="historicalprotocoldeviationviolation",
            name="missed_dose_accountability",
            field=models.TextField(
                blank=True, default="", verbose_name="Who is primarily responsible?"
            ),
        ),
        migrations.AddField(
            model_name="historicalprotocoldeviationviolation",
            name="missed_dose_conditions",
            field=models.CharField(
                choices=[
                    (
                        "MISSED_GT_2D_INDUCTION_RX",
                        "Missed >2 days INDUCTION Rx (>2 doses FLU and/or >8 doses 5FC)",
                    ),
                    (
                        "MISSED_GT_14D_CONSOLIDATION_RX",
                        "Missed >14 days CONSOLIDATION Rx (800mg fluconazole)",
                    ),
                    (
                        "MISSED_GT_14D_MAINTENANCE_RX",
                        "Missed >14 days MAINTENANCE Rx (200mg fluconazole)",
                    ),
                    ("ENROLLED_IN_ERROR", "Ppt enrolled in error"),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                max_length=50,
                verbose_name="Which conditions apply?",
            ),
        ),
        migrations.AddField(
            model_name="historicalprotocoldeviationviolation",
            name="missed_dose_count_summary",
            field=models.TextField(
                blank=True, default="", verbose_name="How many / of what / when?"
            ),
        ),
        migrations.AddField(
            model_name="historicalprotocoldeviationviolation",
            name="missed_dose_reason",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Reasons given by ppts for missed induction doses",
            ),
        ),
        migrations.AddField(
            model_name="protocoldeviationviolation",
            name="missed_dose_accountability",
            field=models.TextField(
                blank=True, default="", verbose_name="Who is primarily responsible?"
            ),
        ),
        migrations.AddField(
            model_name="protocoldeviationviolation",
            name="missed_dose_conditions",
            field=models.CharField(
                choices=[
                    (
                        "MISSED_GT_2D_INDUCTION_RX",
                        "Missed >2 days INDUCTION Rx (>2 doses FLU and/or >8 doses 5FC)",
                    ),
                    (
                        "MISSED_GT_14D_CONSOLIDATION_RX",
                        "Missed >14 days CONSOLIDATION Rx (800mg fluconazole)",
                    ),
                    (
                        "MISSED_GT_14D_MAINTENANCE_RX",
                        "Missed >14 days MAINTENANCE Rx (200mg fluconazole)",
                    ),
                    ("ENROLLED_IN_ERROR", "Ppt enrolled in error"),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                max_length=50,
                verbose_name="Which conditions apply?",
            ),
        ),
        migrations.AddField(
            model_name="protocoldeviationviolation",
            name="missed_dose_count_summary",
            field=models.TextField(
                blank=True, default="", verbose_name="How many / of what / when?"
            ),
        ),
        migrations.AddField(
            model_name="protocoldeviationviolation",
            name="missed_dose_reason",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Reasons given by ppts for missed induction doses",
            ),
        ),
    ]
