# Generated by Django 5.2.10 on 2026-04-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "effect_prn",
            "0026_remove_historicalprotocoldeviationviolation_action_required_followup_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalprotocoldeviationviolation",
            name="missed_dose_accountability",
        ),
        migrations.RemoveField(
            model_name="protocoldeviationviolation",
            name="missed_dose_accountability",
        ),
        migrations.AddField(
            model_name="historicalprotocoldeviationviolation",
            name="missed_dose_responsibility",
            field=models.TextField(
                choices=[
                    ("study_staff", "Study staff"),
                    ("routine care staff", "Routine care staff"),
                    ("participant_error", "Participant error"),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                verbose_name="Who is primarily responsible?",
            ),
        ),
        migrations.AddField(
            model_name="protocoldeviationviolation",
            name="missed_dose_responsibility",
            field=models.TextField(
                choices=[
                    ("study_staff", "Study staff"),
                    ("routine care staff", "Routine care staff"),
                    ("participant_error", "Participant error"),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                verbose_name="Who is primarily responsible?",
            ),
        ),
    ]
