# Generated by Django 5.2.10 on 2026-04-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_lists", "0017_misseddoseresponsibility"),
        (
            "effect_prn",
            "0028_remove_historicalprotocoldeviationviolation_missed_dose_responsibility_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocoldeviationviolation",
            name="missed_dose_responsibility",
            field=models.ManyToManyField(
                blank=True,
                to="effect_lists.misseddoseresponsibility",
                verbose_name="Who is primarily responsible?",
            ),
        ),
    ]
