# Generated by Django 5.2.10 on 2026-04-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "effect_prn",
            "0029_alter_protocoldeviationviolation_missed_dose_responsibility",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallosstofollowup",
            name="number_consecutive_missed_visits",
            field=models.IntegerField(
                null=True, verbose_name="Number of consecutive visits missed"
            ),
        ),
        migrations.AlterField(
            model_name="losstofollowup",
            name="number_consecutive_missed_visits",
            field=models.IntegerField(
                null=True, verbose_name="Number of consecutive visits missed"
            ),
        ),
    ]
