# Generated by Django 6.0.4 on 2026-05-07 23:04

import _socket
import django.db.models.deletion
import django.utils.timezone
import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
import django_audit_fields.fields.uuid_auto_field
import django_revision.revision_field
import edc_sites.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "effect_lists",
            "0018_alter_antibiotics_options_alter_arvregimens_options_and_more",
        ),
        (
            "effect_prn",
            "0030_alter_historicallosstofollowup_number_consecutive_missed_visits_and_more",
        ),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArvSummary",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="System field. From git repository (tag:branch:commit), project metadata, project toml, project VERSION, or settings.",
                        max_length=75,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        default="",
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        default="",
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        default="",
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Device created",
                    ),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Device modified",
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject_identifier", models.CharField(max_length=50, unique=True)),
                (
                    "art_at_screening",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        help_text="AT SCREENING, as opposed to at CrAg test or prior",
                        max_length=255,
                        verbose_name="Was ppt on ARVs at the time of SCREENING?",
                    ),
                ),
                (
                    "art_start_date_known",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("N/A", "Not applicable"),
                        ],
                        max_length=255,
                        verbose_name="Is the most recent start/restart date of this ARV regimen known?",
                    ),
                ),
                (
                    "art_start_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Most recent start/restart date of this ARV regimen?",
                    ),
                ),
                (
                    "art_cont_enrol",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("N/A", "Not applicable"),
                        ],
                        max_length=255,
                        verbose_name="Were ARVs continued AT enrolment?",
                    ),
                ),
                (
                    "art_changed_enrol",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes, ART was changed"),
                            ("No", "No, ART was not changed"),
                            ("unknown", "Unknown"),
                            ("N/A", "Not applicable"),
                        ],
                        max_length=255,
                        verbose_name="Were ARVs changed AT enrolment?",
                    ),
                ),
                (
                    "art_after_enrol",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("N/A", "Not applicable"),
                        ],
                        max_length=255,
                        verbose_name="Were ARVs continued AFTER enrolment?",
                    ),
                ),
                (
                    "art_after_enrol_startdate",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Most recent start/restart date of the ARV regimen continued AFTER enrolment?",
                    ),
                ),
                (
                    "art_after_enrol_regimen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arv_summary_after_enrol",
                        to="effect_lists.arvregimens",
                        verbose_name="What ARV regimen did the participant continued AFTER enrolment?",
                    ),
                ),
                (
                    "art_regimen_at_screening",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required if on an ART at screening",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arv_summary_screening",
                        to="effect_lists.arvregimens",
                        verbose_name="What ARV regimen was the participant taking at the time of screening?",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arv summary",
                "verbose_name_plural": "Arv summaries",
            },
            managers=[
                ("on_site", edc_sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
