# Generated by Django 6.0.4 on 2026-05-07 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "effect_lists",
            "0018_alter_antibiotics_options_alter_arvregimens_options_and_more",
        ),
        ("effect_prn", "0031_arvsummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="arvsummary",
            name="art_changed_enrol_regimen",
            field=models.ForeignKey(
                blank=True,
                help_text="Required if on an ART at screening",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="arv_summary_at_enrol",
                to="effect_lists.arvregimens",
                verbose_name="What ARV regimen was the participant taking at enrolment?",
            ),
        ),
    ]
