# Generated by Django 6.0.4 on 2026-05-08 00:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "effect_lists",
            "0018_alter_antibiotics_options_alter_arvregimens_options_and_more",
        ),
        ("effect_prn", "0032_arvsummary_art_changed_enrol_regimen"),
    ]

    operations = [
        migrations.AddField(
            model_name="arvsummary",
            name="report_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="arvsummary",
            name="art_changed_enrol_regimen",
            field=models.ForeignKey(
                blank=True,
                help_text="Required if ARV regimen changed at enrolment",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="arv_summary_at_enrol",
                to="effect_lists.arvregimens",
                verbose_name="What ARV regimen was the participant taking at enrolment?",
            ),
        ),
    ]
