# Generated by Django 6.0.4 on 2026-05-08 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "effect_lists",
            "0018_alter_antibiotics_options_alter_arvregimens_options_and_more",
        ),
        ("effect_prn", "0033_arvsummary_report_datetime_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="arvsummary",
            old_name="art_at_screening",
            new_name="at_screening",
        ),
        migrations.RenameField(
            model_name="arvsummary",
            old_name="art_start_date",
            new_name="at_screening_start_date",
        ),
        migrations.RenameField(
            model_name="arvsummary",
            old_name="art_start_date_known",
            new_name="at_screening_start_date_known",
        ),
        migrations.RenameField(
            model_name="arvsummary",
            old_name="art_cont_enrol",
            new_name="cont_enrol",
        ),
        migrations.RenameField(
            model_name="arvsummary",
            old_name="art_changed_enrol",
            new_name="cont_enrol_changed",
        ),
        migrations.RenameField(
            model_name="arvsummary",
            old_name="art_changed_enrol_regimen",
            new_name="cont_enrol_regimen",
        ),
        migrations.RemoveField(
            model_name="arvsummary",
            name="art_regimen_at_screening",
        ),
        migrations.AddField(
            model_name="arvsummary",
            name="at_screening_regimen",
            field=models.ForeignKey(
                blank=True,
                help_text="Applicable if on an ART at screening",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="arv_summary_screening",
                to="effect_lists.arvregimens",
                verbose_name="If Yes, what ARV regimen was the participant taking at screening?",
            ),
        ),
    ]
