# Generated by Django 6.0.4 on 2026-05-08 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("effect_prn", "0034_rename_art_at_screening_arvsummary_at_screening_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="arvsummary",
            old_name="art_after_enrol",
            new_name="after_enrol",
        ),
        migrations.RenameField(
            model_name="arvsummary",
            old_name="art_after_enrol_regimen",
            new_name="after_enrol_regimen",
        ),
        migrations.RenameField(
            model_name="arvsummary",
            old_name="art_after_enrol_startdate",
            new_name="after_enrol_start_date",
        ),
    ]
