# Generated by Django 6.0.4 on 2026-05-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_prn", "0035_rename_art_after_enrol_arvsummary_after_enrol_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="arvsummary",
            name="after_enrol_start_date_known",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="Yes",
                max_length=255,
                verbose_name="Is the most recent start/restart date of this ARV regimen known?",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="arvsummary",
            name="after_enrol_start_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Most recent start/restart date of this ARV regimen",
            ),
        ),
    ]
