# Generated by Django 6.0.4 on 2026-05-08 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "effect_lists",
            "0018_alter_antibiotics_options_alter_arvregimens_options_and_more",
        ),
        ("effect_prn", "0036_arvsummary_after_enrol_start_date_known_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arvsummary",
            name="after_enrol_regimen",
            field=models.ForeignKey(
                blank=True,
                help_text="Applicable if ARV regimen was continued after enrolment",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="arv_summary_after_enrol",
                to="effect_lists.arvregimens",
                verbose_name="What ARV regimen did the participant continued AFTER enrolment?",
            ),
        ),
        migrations.AlterField(
            model_name="arvsummary",
            name="cont_enrol_regimen",
            field=models.ForeignKey(
                blank=True,
                help_text="Applicable if ARV regimen changed at enrolment",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="arv_summary_at_enrol",
                to="effect_lists.arvregimens",
                verbose_name="What ARV regimen was the participant taking at enrolment?",
            ),
        ),
    ]
