# Generated by Django 6.0.4 on 2026-05-08 02:54

import _socket
import django.db.models.deletion
import django.utils.timezone
import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
import django_audit_fields.fields.uuid_auto_field
import django_revision.revision_field
import edc_sites.managers
import effect_prn.models.arv_summary
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "effect_lists",
            "0018_alter_antibiotics_options_alter_arvregimens_options_and_more",
        ),
        ("effect_prn", "0037_alter_arvsummary_after_enrol_regimen_and_more"),
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="arvsummary",
            managers=[
                ("objects", effect_prn.models.arv_summary.MyManager()),
                ("on_site", edc_sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalArvSummary",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="System field. From git repository (tag:branch:commit), project metadata, project toml, project VERSION, or settings.",
                        max_length=75,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        default="",
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        default="",
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        default="",
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Device created",
                    ),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Device modified",
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                    ),
                ),
                ("subject_identifier", models.CharField(db_index=True, max_length=50)),
                (
                    "report_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "at_screening",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        help_text="AT SCREENING, as opposed to at CrAg test or prior",
                        max_length=255,
                        verbose_name="Was ppt on ARVs at the time of SCREENING?",
                    ),
                ),
                (
                    "at_screening_start_date_known",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("N/A", "Not applicable"),
                        ],
                        max_length=255,
                        verbose_name="Is the most recent start/restart date of this ARV regimen known?",
                    ),
                ),
                (
                    "at_screening_start_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Most recent start/restart date of this ARV regimen?",
                    ),
                ),
                (
                    "cont_enrol",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("N/A", "Not applicable"),
                        ],
                        max_length=255,
                        verbose_name="Were ARVs continued AT enrolment?",
                    ),
                ),
                (
                    "cont_enrol_changed",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes, ART was changed"),
                            ("No", "No, ART was not changed"),
                            ("unknown", "Unknown"),
                            ("N/A", "Not applicable"),
                        ],
                        max_length=255,
                        verbose_name="Were ARVs changed AT enrolment?",
                    ),
                ),
                (
                    "after_enrol",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("N/A", "Not applicable"),
                        ],
                        max_length=255,
                        verbose_name="Were ARVs continued AFTER enrolment?",
                    ),
                ),
                (
                    "after_enrol_start_date_known",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("N/A", "Not applicable"),
                        ],
                        max_length=255,
                        verbose_name="Is the most recent start/restart date of this ARV regimen known?",
                    ),
                ),
                (
                    "after_enrol_start_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Most recent start/restart date of this ARV regimen",
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "after_enrol_regimen",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Applicable if ARV regimen was continued after enrolment",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="effect_lists.arvregimens",
                        verbose_name="What ARV regimen did the participant continued AFTER enrolment?",
                    ),
                ),
                (
                    "at_screening_regimen",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Applicable if on an ART at screening",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="effect_lists.arvregimens",
                        verbose_name="If Yes, what ARV regimen was the participant taking at screening?",
                    ),
                ),
                (
                    "cont_enrol_regimen",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Applicable if ARV regimen changed at enrolment",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="effect_lists.arvregimens",
                        verbose_name="What ARV regimen was the participant taking at enrolment?",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Arv summary",
                "verbose_name_plural": "historical Arv summaries",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
