# Generated by Django 6.0.5 on 2026-06-01 15:29

import django.db.models.deletion
import edc_model.models.fields.other_charfield
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "effect_lists",
            "0018_alter_antibiotics_options_alter_arvregimens_options_and_more",
        ),
        ("effect_prn", "0038_alter_arvsummary_managers_historicalarvsummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="arvsummary",
            name="at_screening_regimen_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If other, please specify ...",
            ),
        ),
        migrations.AddField(
            model_name="historicalarvsummary",
            name="at_screening_regimen_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If other, please specify ...",
            ),
        ),
        migrations.AlterField(
            model_name="arvsummary",
            name="after_enrol",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No, Not started or restarted from enrolment to EoS"),
                    ("N/A", "Not applicable, already on ART at enrolment"),
                ],
                help_text="See column W on excel",
                max_length=255,
                verbose_name="Were ARVs started or restarted AFTER enrolment?",
            ),
        ),
        migrations.AlterField(
            model_name="arvsummary",
            name="after_enrol_regimen",
            field=models.ForeignKey(
                blank=True,
                help_text="Q11: Applicable if ARV regimen was started or restarted after enrolment",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="arv_summary_after_enrol",
                to="effect_lists.arvregimens",
                verbose_name="What ARV regimen did the participant start or restart AFTER enrolment?",
            ),
        ),
        migrations.AlterField(
            model_name="arvsummary",
            name="at_screening_start_date",
            field=models.DateField(
                blank=True,
                help_text="From excel: When was this regimen MOST RECENTLY started or restarted?",
                null=True,
                verbose_name="Most recent start/restart date of this ARV regimen?",
            ),
        ),
        migrations.AlterField(
            model_name="arvsummary",
            name="cont_enrol",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No, Not started or restarted from enrolment to EoS"),
                    ("N/A", "Not applicable, already on ART at enrolment"),
                ],
                max_length=255,
                verbose_name="Were ARVs started or restarted after enrolment?",
            ),
        ),
        migrations.AlterField(
            model_name="arvsummary",
            name="cont_enrol_changed",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes, ART was changed"),
                    ("No", "No, ART was not changed"),
                    ("unknown", "Unknown"),
                    ("N/A", "Not applicable"),
                ],
                help_text="from excel: column W",
                max_length=255,
                verbose_name="What ARV regimen did the participant start AFTER enrolment??",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarvsummary",
            name="after_enrol",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No, Not started or restarted from enrolment to EoS"),
                    ("N/A", "Not applicable, already on ART at enrolment"),
                ],
                help_text="See column W on excel",
                max_length=255,
                verbose_name="Were ARVs started or restarted AFTER enrolment?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarvsummary",
            name="after_enrol_regimen",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Q11: Applicable if ARV regimen was started or restarted after enrolment",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="effect_lists.arvregimens",
                verbose_name="What ARV regimen did the participant start or restart AFTER enrolment?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarvsummary",
            name="at_screening_start_date",
            field=models.DateField(
                blank=True,
                help_text="From excel: When was this regimen MOST RECENTLY started or restarted?",
                null=True,
                verbose_name="Most recent start/restart date of this ARV regimen?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarvsummary",
            name="cont_enrol",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No, Not started or restarted from enrolment to EoS"),
                    ("N/A", "Not applicable, already on ART at enrolment"),
                ],
                max_length=255,
                verbose_name="Were ARVs started or restarted after enrolment?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarvsummary",
            name="cont_enrol_changed",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes, ART was changed"),
                    ("No", "No, ART was not changed"),
                    ("unknown", "Unknown"),
                    ("N/A", "Not applicable"),
                ],
                help_text="from excel: column W",
                max_length=255,
                verbose_name="What ARV regimen did the participant start AFTER enrolment??",
            ),
        ),
    ]
