# Generated by Django 6.0.5 on 2026-06-01 20:24

import django.db.models.deletion
import edc_model.models.fields.other_charfield
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "effect_lists",
            "0018_alter_antibiotics_options_alter_arvregimens_options_and_more",
        ),
        ("effect_prn", "0039_arvsummary_at_screening_regimen_other_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="arvsummary",
            name="after_enrol",
        ),
        migrations.RemoveField(
            model_name="arvsummary",
            name="after_enrol_regimen",
        ),
        migrations.RemoveField(
            model_name="arvsummary",
            name="after_enrol_start_date_known",
        ),
        migrations.RemoveField(
            model_name="historicalarvsummary",
            name="after_enrol",
        ),
        migrations.RemoveField(
            model_name="historicalarvsummary",
            name="after_enrol_regimen",
        ),
        migrations.RemoveField(
            model_name="historicalarvsummary",
            name="after_enrol_start_date_known",
        ),
        migrations.AddField(
            model_name="arvsummary",
            name="cont_enrol_regimen_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If other, please specify ...",
            ),
        ),
        migrations.AddField(
            model_name="arvsummary",
            name="cont_enrol_regimen_start_date_known",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="",
                max_length=255,
                verbose_name="Is the start date of this ARV regimen known?",
            ),
        ),
        migrations.AddField(
            model_name="arvsummary",
            name="cont_enrol_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Start date of this ARV regimen"
            ),
        ),
        migrations.AddField(
            model_name="historicalarvsummary",
            name="cont_enrol_regimen_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If other, please specify ...",
            ),
        ),
        migrations.AddField(
            model_name="historicalarvsummary",
            name="cont_enrol_regimen_start_date_known",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="",
                max_length=255,
                verbose_name="Is the start date of this ARV regimen known?",
            ),
        ),
        migrations.AddField(
            model_name="historicalarvsummary",
            name="cont_enrol_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Start date of this ARV regimen"
            ),
        ),
        migrations.AlterField(
            model_name="arvsummary",
            name="at_screening_start_date_known",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="",
                max_length=255,
                verbose_name="Is the most recent start/restart date of this ARV regimen known?",
            ),
        ),
        migrations.AlterField(
            model_name="arvsummary",
            name="cont_enrol",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes, regimen unchanged"),
                    ("No", "No"),
                    ("N/A", "Not applicable, not on ART at time of screening"),
                ],
                max_length=255,
                verbose_name="Was ART continued at enrolment?",
            ),
        ),
        migrations.AlterField(
            model_name="arvsummary",
            name="cont_enrol_changed",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes, ART was changed"),
                    ("No", "No, ART was not changed"),
                    ("unknown", "Unknown"),
                    ("N/A", "Not applicable"),
                ],
                default="",
                help_text="If No, from excel: column W",
                max_length=255,
                verbose_name="If ART continued at enrolment, was the regimen changed?",
            ),
        ),
        migrations.AlterField(
            model_name="arvsummary",
            name="cont_enrol_regimen",
            field=models.ForeignKey(
                blank=True,
                help_text="Applicable if ARV regimen changed at enrolment",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="arv_summary_at_enrol",
                to="effect_lists.arvregimens",
                verbose_name="If changed, what was the new ARV regimen?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarvsummary",
            name="at_screening_start_date_known",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="",
                max_length=255,
                verbose_name="Is the most recent start/restart date of this ARV regimen known?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarvsummary",
            name="cont_enrol",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes, regimen unchanged"),
                    ("No", "No"),
                    ("N/A", "Not applicable, not on ART at time of screening"),
                ],
                max_length=255,
                verbose_name="Was ART continued at enrolment?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarvsummary",
            name="cont_enrol_changed",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes, ART was changed"),
                    ("No", "No, ART was not changed"),
                    ("unknown", "Unknown"),
                    ("N/A", "Not applicable"),
                ],
                default="",
                help_text="If No, from excel: column W",
                max_length=255,
                verbose_name="If ART continued at enrolment, was the regimen changed?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarvsummary",
            name="cont_enrol_regimen",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Applicable if ARV regimen changed at enrolment",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="effect_lists.arvregimens",
                verbose_name="If changed, what was the new ARV regimen?",
            ),
        ),
    ]
