# Generated by Django 6.0.5 on 2026-06-01 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("effect_prn", "0040_remove_arvsummary_after_enrol_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="arvsummary",
            old_name="at_screening_start_date",
            new_name="at_screening_regimen_start_date",
        ),
        migrations.RenameField(
            model_name="arvsummary",
            old_name="at_screening_start_date_known",
            new_name="at_screening_regimen_start_date_known",
        ),
        migrations.RenameField(
            model_name="arvsummary",
            old_name="cont_enrol_start_date",
            new_name="cont_enrol_regimen_start_date",
        ),
        migrations.RenameField(
            model_name="historicalarvsummary",
            old_name="at_screening_start_date",
            new_name="at_screening_regimen_start_date",
        ),
        migrations.RenameField(
            model_name="historicalarvsummary",
            old_name="at_screening_start_date_known",
            new_name="at_screening_regimen_start_date_known",
        ),
        migrations.RenameField(
            model_name="historicalarvsummary",
            old_name="cont_enrol_start_date",
            new_name="cont_enrol_regimen_start_date",
        ),
    ]
