# Generated by Django 6.0.5 on 2026-06-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "effect_prn",
            "0041_rename_at_screening_start_date_arvsummary_at_screening_regimen_start_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="arvsummary",
            name="cont_enrol_changed",
        ),
        migrations.RemoveField(
            model_name="historicalarvsummary",
            name="cont_enrol_changed",
        ),
        migrations.AddField(
            model_name="arvsummary",
            name="cont_enrol_regimen_changed",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes, ART was changed"),
                    ("No", "No, ART was not changed"),
                    ("unknown", "Unknown"),
                    ("N/A", "Not applicable"),
                ],
                default="",
                help_text="If No, from excel: column W",
                max_length=255,
                verbose_name="If YES, ART continued at enrolment, was the regimen changed?",
            ),
        ),
        migrations.AddField(
            model_name="historicalarvsummary",
            name="cont_enrol_regimen_changed",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes, ART was changed"),
                    ("No", "No, ART was not changed"),
                    ("unknown", "Unknown"),
                    ("N/A", "Not applicable"),
                ],
                default="",
                help_text="If No, from excel: column W",
                max_length=255,
                verbose_name="If YES, ART continued at enrolment, was the regimen changed?",
            ),
        ),
        migrations.AlterField(
            model_name="arvsummary",
            name="cont_enrol",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("N/A", "Not applicable, not on ART at time of screening"),
                ],
                max_length=255,
                verbose_name="Was ART continued at enrolment?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarvsummary",
            name="cont_enrol",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("N/A", "Not applicable, not on ART at time of screening"),
                ],
                max_length=255,
                verbose_name="Was ART continued at enrolment?",
            ),
        ),
    ]
