# Generated by Django 6.0.5 on 2026-06-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_prn", "0042_remove_arvsummary_cont_enrol_changed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="arvsummary",
            name="cont_enrol_ever_restarted",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="",
                max_length=255,
                verbose_name="If not continued at enrolment, was ART ever restarted before EoS?",
            ),
        ),
        migrations.AddField(
            model_name="historicalarvsummary",
            name="cont_enrol_ever_restarted",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="",
                max_length=255,
                verbose_name="If not continued at enrolment, was ART ever restarted before EoS?",
            ),
        ),
    ]
