# Generated by Django 6.0.5 on 2026-06-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_prn", "0043_arvsummary_cont_enrol_ever_restarted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arvsummary",
            name="cont_enrol_ever_restarted",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("unknown", "Unknown")],
                default="",
                max_length=255,
                verbose_name="If not continued at enrolment, was ART ever restarted before EoS?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarvsummary",
            name="cont_enrol_ever_restarted",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("unknown", "Unknown")],
                default="",
                max_length=255,
                verbose_name="If not continued at enrolment, was ART ever restarted before EoS?",
            ),
        ),
    ]
