# Generated by Django 3.2.8 on 2022-03-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("effect_subject", "0029_auto_20220324_1825"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adherence",
            name="diary_match_medication",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="N/A",
                max_length=15,
                verbose_name="Did the patient adherence diary match the medication reconciliation?",
            ),
        ),
        migrations.AlterField(
            model_name="adherence",
            name="medication_reconciliation",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="N/A",
                max_length=15,
                verbose_name="Was a medication reconciliation conducted?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaladherence",
            name="diary_match_medication",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="N/A",
                max_length=15,
                verbose_name="Did the patient adherence diary match the medication reconciliation?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaladherence",
            name="medication_reconciliation",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="N/A",
                max_length=15,
                verbose_name="Was a medication reconciliation conducted?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaladherencestagefour",
            name="diary_match_medication",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="N/A",
                max_length=15,
                verbose_name="Did the patient adherence diary match the medication reconciliation?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaladherencestagefour",
            name="medication_reconciliation",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="N/A",
                max_length=15,
                verbose_name="Was a medication reconciliation conducted?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaladherencestageone",
            name="diary_match_medication",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="N/A",
                max_length=15,
                verbose_name="Did the patient adherence diary match the medication reconciliation?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaladherencestageone",
            name="medication_reconciliation",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="N/A",
                max_length=15,
                verbose_name="Was a medication reconciliation conducted?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaladherencestagethree",
            name="diary_match_medication",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="N/A",
                max_length=15,
                verbose_name="Did the patient adherence diary match the medication reconciliation?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaladherencestagethree",
            name="medication_reconciliation",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="N/A",
                max_length=15,
                verbose_name="Was a medication reconciliation conducted?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaladherencestagetwo",
            name="diary_match_medication",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="N/A",
                max_length=15,
                verbose_name="Did the patient adherence diary match the medication reconciliation?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaladherencestagetwo",
            name="medication_reconciliation",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="N/A",
                max_length=15,
                verbose_name="Was a medication reconciliation conducted?",
            ),
        ),
    ]
