# Generated by Django 3.2.13 on 2022-06-23 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("effect_subject", "0075_auto_20220615_1705"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalsignsandsymptoms",
            old_name="headache_duration_microseconds",
            new_name="calculated_headache_duration",
        ),
        migrations.RenameField(
            model_name="signsandsymptoms",
            old_name="headache_duration_microseconds",
            new_name="calculated_headache_duration",
        ),
    ]
