# Generated by Django 3.2.13 on 2022-07-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("effect_subject", "0080_auto_20220708_1652"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicaladherence",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Adherence",
                "verbose_name_plural": "historical Adherence",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaladherencestagefour",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Adherence: Day 14+",
                "verbose_name_plural": "historical Adherence: Day 14+",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaladherencestageone",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Adherence: Day 1",
                "verbose_name_plural": "historical Adherence: Day 1",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaladherencestagethree",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Adherence: Day 14",
                "verbose_name_plural": "historical Adherence: Day 14",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaladherencestagetwo",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Adherence: On study",
                "verbose_name_plural": "historical Adherence: On study",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalarvhistory",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical ARV History",
                "verbose_name_plural": "historical ARV History",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalarvtreatment",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical ARV Treatment",
                "verbose_name_plural": "historical ARV Treatment",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalbloodculture",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Blood culture",
                "verbose_name_plural": "historical Blood culture",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalbloodresultschem",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Blood Result: Chemistry",
                "verbose_name_plural": "historical Blood Results: Chemistry",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalbloodresultsfbc",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Blood Result: FBC",
                "verbose_name_plural": "historical Blood Results: FBC",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalchestxray",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Chest X-ray",
                "verbose_name_plural": "historical Chest X-rays",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalclinicalnote",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Clinical Note",
                "verbose_name_plural": "historical Clinical Note",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldiagnoses",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Significant Diagnoses",
                "verbose_name_plural": "historical Significant Diagnoses",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalhealtheconomics",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Health Economics",
                "verbose_name_plural": "historical Health Economics",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalhistopathology",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Histopathology",
                "verbose_name_plural": "historical Histopathology",
            },
        ),
        migrations.AlterModelOptions(
            name="historicallpcsf",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Lumbar Puncture/CSF",
                "verbose_name_plural": "historical Lumbar Puncture/CSF",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmedicationadherence",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Medication Adherence",
                "verbose_name_plural": "historical Medication Adherence",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmentalstatus",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Mental Status",
                "verbose_name_plural": "historical Mental Status",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpatienthistory",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Patient History",
                "verbose_name_plural": "historical Patient History",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpatienttreatment",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Patient Treatment",
                "verbose_name_plural": "historical Patient Treatment",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsignsandsymptoms",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Signs and Symptoms",
                "verbose_name_plural": "historical Signs and Symptoms",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalstudymedication",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Study medication",
                "verbose_name_plural": "historical Study medication",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalstudymedicationbaseline",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Study medication (Baseline)",
                "verbose_name_plural": "historical Study medication (Baseline)",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalstudymedicationfollowup",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Study medication",
                "verbose_name_plural": "historical Study medication",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsubjectrequisition",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical subject requisition",
                "verbose_name_plural": "historical subject requisitions",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsubjectvisit",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical subject visit",
                "verbose_name_plural": "historical subject visits",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsubjectvisitmissed",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Missed Visit Report",
                "verbose_name_plural": "historical Missed Visit Report",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaltbdiagnostics",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical TB Diagnostics",
                "verbose_name_plural": "historical TB Diagnostics",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalurinalysis",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Urinalysis",
                "verbose_name_plural": "historical Urinalysis",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalvitalsigns",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Vital Signs",
                "verbose_name_plural": "historical Vital Signs",
            },
        ),
        migrations.AlterField(
            model_name="historicaladherence",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaladherencestagefour",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaladherencestageone",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaladherencestagethree",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaladherencestagetwo",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalarvhistory",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalarvtreatment",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalbloodculture",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalbloodresultschem",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalbloodresultsfbc",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalchestxray",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalclinicalnote",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaldiagnoses",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalhealtheconomics",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalhistopathology",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicallpcsf",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalmedicationadherence",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalmentalstatus",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpatienthistory",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpatienttreatment",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalsignsandsymptoms",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalstudymedication",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalstudymedicationbaseline",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalstudymedicationfollowup",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalsubjectrequisition",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalsubjectvisit",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalsubjectvisitmissed",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaltbdiagnostics",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalurinalysis",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalvitalsigns",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
