# Generated by Django 3.2.13 on 2022-07-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("effect_subject", "0084_auto_20220729_1805"),
    ]

    operations = [
        migrations.AddField(
            model_name="healtheconomicsevent",
            name="admitted",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                null=True,
                verbose_name="Was the participant admitted as part of this health event?",
            ),
        ),
        migrations.AddField(
            model_name="historicalhealtheconomicsevent",
            name="admitted",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                null=True,
                verbose_name="Was the participant admitted as part of this health event?",
            ),
        ),
        migrations.AlterField(
            model_name="healtheconomicsevent",
            name="admitted_kith_kin_time_off",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No (employed but did not take time off)"),
                    ("N/A", "Not applicable (includes not employed)"),
                ],
                default="N/A",
                max_length=15,
                verbose_name="Did a family member/friend have to take time off work to stay with you or to come see you during your hospital stay?",
            ),
        ),
        migrations.AlterField(
            model_name="healtheconomicsevent",
            name="admitted_time_off",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No (employed but did not take time off)"),
                    ("N/A", "Not applicable (includes not employed)"),
                ],
                default="N/A",
                max_length=15,
                verbose_name="Did you have to take time off work because of being admitted?",
            ),
        ),
        migrations.AlterField(
            model_name="healtheconomicsevent",
            name="lost_income",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No (employed but did not lose earnings)"),
                    ("N/A", "Not applicable (includes not employed)"),
                ],
                default="N/A",
                max_length=15,
                verbose_name="Did you lose earnings as a result?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhealtheconomicsevent",
            name="admitted_kith_kin_time_off",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No (employed but did not take time off)"),
                    ("N/A", "Not applicable (includes not employed)"),
                ],
                default="N/A",
                max_length=15,
                verbose_name="Did a family member/friend have to take time off work to stay with you or to come see you during your hospital stay?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhealtheconomicsevent",
            name="admitted_time_off",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No (employed but did not take time off)"),
                    ("N/A", "Not applicable (includes not employed)"),
                ],
                default="N/A",
                max_length=15,
                verbose_name="Did you have to take time off work because of being admitted?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhealtheconomicsevent",
            name="lost_income",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No (employed but did not lose earnings)"),
                    ("N/A", "Not applicable (includes not employed)"),
                ],
                default="N/A",
                max_length=15,
                verbose_name="Did you lose earnings as a result?",
            ),
        ),
    ]
