# Generated by Django 4.1.7 on 2023-08-02 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("effect_subject", "0103_historicalparticipanthistory_admission_indication_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallpcsf",
            name="csf_requisition",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Start typing the requisition identifier or select one from this visit",
                limit_choices_to={"panel__name": "csf_culture"},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="effect_subject.subjectrequisition",
                verbose_name="CSF Requisition",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltbdiagnostics",
            name="sputum_requisition",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Start typing the requisition identifier or select one from this visit",
                limit_choices_to={"panel__name": "sputum"},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="effect_subject.subjectrequisition",
                verbose_name="Sputum requisition",
            ),
        ),
        migrations.AlterField(
            model_name="lpcsf",
            name="csf_requisition",
            field=models.ForeignKey(
                blank=True,
                help_text="Start typing the requisition identifier or select one from this visit",
                limit_choices_to={"panel__name": "csf_culture"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="csfrequisition",
                to="effect_subject.subjectrequisition",
                verbose_name="CSF Requisition",
            ),
        ),
        migrations.AlterField(
            model_name="tbdiagnostics",
            name="sputum_requisition",
            field=models.ForeignKey(
                blank=True,
                help_text="Start typing the requisition identifier or select one from this visit",
                limit_choices_to={"panel__name": "sputum"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="effect_subject.subjectrequisition",
                verbose_name="Sputum requisition",
            ),
        ),
    ]
