# Generated by Django 5.1.1 on 2024-09-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_subject", "0117_bloodresultschem_sodium_abnormal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodresultschem",
            name="crp_units",
            field=models.CharField(
                blank=True,
                choices=[("mg/dL", "mg/dL"), ("mg/L", "mg/L")],
                max_length=15,
                null=True,
                verbose_name="units",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbloodresultschem",
            name="crp_units",
            field=models.CharField(
                blank=True,
                choices=[("mg/dL", "mg/dL"), ("mg/L", "mg/L")],
                max_length=15,
                null=True,
                verbose_name="units",
            ),
        ),
    ]
