# Generated by Django 5.1.3 on 2025-01-10 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """Note: Migrations effect_subject/migrations/0119-0123 are all
    related, and expected to be run together.  See also ticket #658.
    """

    dependencies = [
        (
            "effect_subject",
            "0119_rename_viral_load_result_arvhistory_retired_viral_load_result_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="arvhistory",
            name="viral_load_quantifier",
            field=models.CharField(
                choices=[("=", "="), (">", ">"), ("<", "<"), ("N/A", "Not applicable")],
                help_text="If lower than detection limit (LDL), use '<' and enter the lab detection limit value above.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="arvhistory",
            name="viral_load_result",
            field=models.IntegerField(
                blank=True,
                help_text="copies/mL",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9999999),
                ],
                verbose_name="Viral load result",
            ),
        ),
        migrations.AddField(
            model_name="historicalarvhistory",
            name="viral_load_quantifier",
            field=models.CharField(
                choices=[("=", "="), (">", ">"), ("<", "<"), ("N/A", "Not applicable")],
                help_text="If lower than detection limit (LDL), use '<' and enter the lab detection limit value above.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalarvhistory",
            name="viral_load_result",
            field=models.IntegerField(
                blank=True,
                help_text="copies/mL",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9999999),
                ],
                verbose_name="Viral load result",
            ),
        ),
    ]
