# Generated by Django 5.2.1 on 2025-06-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("effect_subject", "0123_alter_arvhistory_retired_viral_load_result_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodresultschem",
            name="tbil_units",
            field=models.CharField(
                blank=True,
                choices=[("mg/dL", "mg/dL"), ("g/L", "g/L"), ("umol/L", "umol/L")],
                max_length=15,
                null=True,
                verbose_name="units",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbloodresultschem",
            name="tbil_units",
            field=models.CharField(
                blank=True,
                choices=[("mg/dL", "mg/dL"), ("g/L", "g/L"), ("umol/L", "umol/L")],
                max_length=15,
                null=True,
                verbose_name="units",
            ),
        ),
    ]
